### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/araymond/joal/JackOfAllTrades : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by Donokami** [anthonyraymond/joal#1]
(Bon j'suis désolé, j'suis une burne en anglais)
Lorsque je démarre Joal pour la première fois sans docker avec une Raspberry Pi 2, je me retrouve avec cette erreur.
![image](https://cloud.githubusercontent.com/assets/5563277/23766769/6e330dda-0506-11e7-9708-b0b4677ea625.png)
Ai-je fais une erreur au niveau de la copie des fichiers de config? Comment régler le souci? 
Merci :)

**Comment by anthonyraymond** [comment]
Bonjour,
essaye de taper `java -version` dans un terminal et dis moi ce que ca te donne. Il faut la version 8 de Java, je suppose que tu en as une plus ancienne.

Quoi qu'il en soit dis moi ce que te donne cette commande, et je te dirais comment régler le problème.

**Comment by Donokami** [comment]
Merci beaucoup ! :)
