### ISSUE TITLE
Error Unregistered torrent

### ISSUE THREAD

**Issue by tugdualnicolas** [anthonyraymond/joal#10]
Bonjour j'ai l'erreur suivante quand je lance le programme que se soit sur W10 ou un vps Debian 8 
Tracker : hdf.world

```
00:56:51.894 [main] INFO  com.turn.ttorrent.common.Torrent - Single-file torrent information:
00:56:51.898 [main] INFO  com.turn.ttorrent.common.Torrent -   Torrent name: KONG_SKULL_ISLAND_3D_HDCLUB.iso
00:56:51.900 [main] INFO  com.turn.ttorrent.common.Torrent -   Announced at:
00:56:51.901 [main] INFO  com.turn.ttorrent.common.Torrent -      1. http://hdf.world:2710/CENSORED/announce
00:56:51.907 [main] INFO  com.turn.ttorrent.common.Torrent -   Created on..: 2017-06-26T18:33:38.000+0200
00:56:51.907 [main] INFO  com.turn.ttorrent.common.Torrent -   Created by..: ruTorrent (PHP Class - Adrien Gibrat)
00:56:51.907 [main] INFO  com.turn.ttorrent.common.Torrent -   Pieces......: 2570 piece(s) (16777216 byte(s)/piece)
00:56:51.908 [main] INFO  com.turn.ttorrent.common.Torrent -   Total size..: 43 109 974 016 byte(s)
00:56:52.038 [main] INFO  org.araymond.joal.ttorent.client.ConnectionHandler - Listening for incoming connections on CENSORED/***.***.143.20:49152.
00:56:52.160 [main] INFO  org.araymond.joal.SeedManager - Start seeding for 1187 minutes.
00:56:52.167 [bt-announce(..6D3470)] INFO  org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes...
00:56:52.552 [bt-announce(..6D3470)] WARN  org.araymond.joal.ttorent.client.Client - 0 peers found for this torrent, stop seeding this torrent.
00:56:52.569 [bt-announce(..6D3470)] INFO  org.araymond.joal.torrent.watcher.TorrentFileProvider - Successfully moved file: /root/joal-conf/resources/torrents/Kong Skull Island - 2017 (Blu-Ray Original - AVC - 3D 108                     0p)-6561.torrent to archive folder
00:56:52.573 [bt-announce(..6D3470)] INFO  org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STOPPED to tracker with 0U/0D/0L bytes...
00:56:57.920 [main] INFO  com.turn.ttorrent.common.Torrent - Multi-file torrent information:
00:56:57.925 [main] INFO  com.turn.ttorrent.common.Torrent -   Torrent name: Inferno.2016.x265.HEVC.1080p.Multi.VFF.VO.DTSHDMA.Sub.Fr.En.GuS2SuG
00:56:57.925 [main] INFO  com.turn.ttorrent.common.Torrent -   Announced at:
00:56:57.926 [main] INFO  com.turn.ttorrent.common.Torrent -      1. http://hdf.world:2710/***/announce
00:56:57.926 [main] INFO  com.turn.ttorrent.common.Torrent -   Created on..: 2017-06-30T16:22:55.000+0200
00:56:57.926 [main] INFO  com.turn.ttorrent.common.Torrent -   Created by..: BitTorrent/7.9.9
00:56:57.927 [main] INFO  com.turn.ttorrent.common.Torrent -   Found 2 file(s) in multi-file torrent structure.
00:56:57.930 [main] INFO  com.turn.ttorrent.common.Torrent -   Pieces......: 1906 piece(s) (8388608 byte(s)/piece)
00:56:57.931 [main] INFO  com.turn.ttorrent.common.Torrent -   Total size..: 15 982 080 109 byte(s)
00:56:57.932 [main] INFO  org.araymond.joal.ttorent.client.ConnectionHandler - Listening for incoming connections on CENSORED/***.***.***.20:49152.
00:56:57.934 [main] INFO  org.araymond.joal.SeedManager - Start seeding for 1185 minutes.
00:56:57.939 [bt-announce(..576972)] INFO  org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes...
00:56:58.283 [bt-announce(..576972)] WARN  org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent
00:57:03.285 [bt-announce(..576972)] INFO  org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes...
00:57:03.643 [bt-announce(..576972)] WARN  org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent
00:57:08.645 [bt-announce(..576972)] INFO  org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes...
00:57:09.007 [bt-announce(..576972)] WARN  org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent
00:57:14.008 [bt-announce(..576972)] INFO  org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes...
00:57:14.329 [bt-announce(..576972)] WARN  org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent
00:57:19.330 [bt-announce(..576972)] INFO  org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes...
00:57:19.659 [bt-announce(..576972)] WARN  org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent
00:57:21.837 [Thread-2] INFO  org.araymond.joal.torrent.watcher.TorrentFileProvider - Torrent file deletion detected, hot deleted file: /root/joal-conf/resou                                                                                rces/torrents/Kong Skull Island - 2017 (Blu-Ray Original - AVC - 3D 1080p)-6561.torrent
00:57:24.660 [bt-announce(..576972)] INFO  org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes...
00:57:25.011 [bt-announce(..576972)] WARN  org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent
00:57:30.013 [bt-announce(..576972)] INFO  org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes...
```

Et ainsi de suite infiniment.

**Comment by anthonyraymond** [comment]
Bonjour,

Cela signifie que le torrent (inferno dans ce cas la), n'est pas/plus disponible sur le tracker (il a dû être supprimer) supprime le du dossier joal-conf/torrent et essaye avec d'autres .torrent :)

Tiens moi au courant pour me dire si ca fonctionne.

Anthony.
On lundi 3 juillet 2017 à 01:01 tugdualnicolas <notifications@github.com> wrote:

Bonjour j'ai l'erreur suivante quand je lance le programme que se soit sur W10 ou un vps Debian 8
Tracker : hdf.world

00:56:51.894 [main] INFO com.turn.ttorrent.common.Torrent - Single-file torrent information: 00:56:51.898 [main] INFO com.turn.ttorrent.common.Torrent - Torrent name: KONG_SKULL_ISLAND_3D_HDCLUB.iso 00:56:51.900 [main] INFO com.turn.ttorrent.common.Torrent - Announced at: 00:56:51.901 [main] INFO com.turn.ttorrent.common.Torrent - 1. http://hdf.world:2710/21f1cc064f0cd2144d97258886697171/announce 00:56:51.907 [main] INFO com.turn.ttorrent.common.Torrent - Created on..: 2017-06-26T18:33:38.000+0200 00:56:51.907 [main] INFO com.turn.ttorrent.common.Torrent - Created by..: ruTorrent (PHP Class - Adrien Gibrat) 00:56:51.907 [main] INFO com.turn.ttorrent.common.Torrent - Pieces......: 2570 piece(s) (16777216 byte(s)/piece) 00:56:51.908 [main] INFO com.turn.ttorrent.common.Torrent - Total size..: 43 109 974 016 byte(s) 00:56:52.038 [main] INFO org.araymond.joal.ttorent.client.ConnectionHandler - Listening for incoming connections on vps-23811.fhnet.fr/188.213.143.20:49152. 00:56:52.160 [main] INFO org.araymond.joal.SeedManager - Start seeding for 1187 minutes. 00:56:52.167 [bt-announce(..6D3470)] INFO org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes... 00:56:52.552 [bt-announce(..6D3470)] WARN org.araymond.joal.ttorent.client.Client - 0 peers found for this torrent, stop seeding this torrent. 00:56:52.569 [bt-announce(..6D3470)] INFO org.araymond.joal.torrent.watcher.TorrentFileProvider - Successfully moved file: /root/joal-conf/resources/torrents/Kong Skull Island - 2017 (Blu-Ray Original - AVC - 3D 108 0p)-6561.torrent to archive folder 00:56:52.573 [bt-announce(..6D3470)] INFO org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STOPPED to tracker with 0U/0D/0L bytes... 00:56:57.920 [main] INFO com.turn.ttorrent.common.Torrent - Multi-file torrent information: 00:56:57.925 [main] INFO com.turn.ttorrent.common.Torrent - Torrent name: Inferno.2016.x265.HEVC.1080p.Multi.VFF.VO.DTSHDMA.Sub.Fr.En.GuS2SuG 00:56:57.925 [main] INFO com.turn.ttorrent.common.Torrent - Announced at: 00:56:57.926 [main] INFO com.turn.ttorrent.common.Torrent - 1. http://hdf.world:2710/21f1cc064f0cd2144d97258886697171/announce 00:56:57.926 [main] INFO com.turn.ttorrent.common.Torrent - Created on..: 2017-06-30T16:22:55.000+0200 00:56:57.926 [main] INFO com.turn.ttorrent.common.Torrent - Created by..: BitTorrent/7.9.9 00:56:57.927 [main] INFO com.turn.ttorrent.common.Torrent - Found 2 file(s) in multi-file torrent structure. 00:56:57.930 [main] INFO com.turn.ttorrent.common.Torrent - Pieces......: 1906 piece(s) (8388608 byte(s)/piece) 00:56:57.931 [main] INFO com.turn.ttorrent.common.Torrent - Total size..: 15 982 080 109 byte(s) 00:56:57.932 [main] INFO org.araymond.joal.ttorent.client.ConnectionHandler - Listening for incoming connections on vps-23811.fhnet.fr/188.213.143.20:49152. 00:56:57.934 [main] INFO org.araymond.joal.SeedManager - Start seeding for 1185 minutes. 00:56:57.939 [bt-announce(..576972)] INFO org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes... 00:56:58.283 [bt-announce(..576972)] WARN org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent 00:57:03.285 [bt-announce(..576972)] INFO org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes... 00:57:03.643 [bt-announce(..576972)] WARN org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent 00:57:08.645 [bt-announce(..576972)] INFO org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes... 00:57:09.007 [bt-announce(..576972)] WARN org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent 00:57:14.008 [bt-announce(..576972)] INFO org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes... 00:57:14.329 [bt-announce(..576972)] WARN org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent 00:57:19.330 [bt-announce(..576972)] INFO org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes... 00:57:19.659 [bt-announce(..576972)] WARN org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent 00:57:21.837 [Thread-2] INFO org.araymond.joal.torrent.watcher.TorrentFileProvider - Torrent file deletion detected, hot deleted file: /root/joal-conf/resou rces/torrents/Kong Skull Island - 2017 (Blu-Ray Original - AVC - 3D 1080p)-6561.torrent 00:57:24.660 [bt-announce(..576972)] INFO org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes... 00:57:25.011 [bt-announce(..576972)] WARN org.araymond.joal.ttorent.client.announce.Announce - Unregistered torrent 00:57:30.013 [bt-announce(..576972)] INFO org.araymond.joal.ttorent.client.announce.HTTPTrackerClient - Announcing STARTED to tracker with 0U/0D/0L bytes... 

Et ainsi de suite infiniment.

**Comment by anthonyraymond** [comment]
Je viens de voir que c'était une issue Github, dans mon élan j'avais répondu par mail. Fait attention tu avait inclus des informations privés (dont ta passkey).
