### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by CoderCore** [anthonyraymond/joal#100]
It seems causes by all torrent files loaded into memory,
Is there any way not to load so many files into memory?

**Comment by anthonyraymond** [comment]
Hi, so far it' not possible. You will have to either remove torrent from the folder OR start the program with the java `-Xmx` argument to increase the JVM memory.

ex if you want to allow the JVM to extend up to 2G memory:
java -Xmx2048m -jar ....
