### ISSUE TITLE
Joal with Docker in Synology NAS - Container crashes after a few seconds

### ISSUE THREAD

**Issue by Boggyb01** [anthonyraymond/joal#104]
Hello,

I have been trying the run JOAl on my Synology, without success so far, the other issues reported haven't helped.

Step 0 : I have put the config.json, clients, and torrents folder here : volume1/docker/Joal. My config location looks like this /
<img width="539" alt="Capture d’écran 2020-09-06 à 18 00 00" src="https://user-images.githubusercontent.com/54419966/92329894-d3de9200-f06a-11ea-8982-c4c9817b8ce0.png">

Step 1 : I have run the following command line to create the container : 

docker run -d \
    -p 9000:9000 \
    -v PATH_TO_CONF:/volume1/docker/Joal \
    --name="joal" \
    anthonyraymond/joal \
    --joal-conf\="/Joal" \
    --spring.main.web-environment\=true \
    --server.port\="9000" \
    --joal.ui.path.prefix\="GUIJOAL" \
    --joal.ui.secret-token\="pass"

The container appeared properly in docker and starts. It then crashes after a 2-3 seconds. Here is the container log, it seems to indicate that the /torrents folder is missing, which oddly isn't the case as per my first image

Any clues ?

Thank you

**Comment by Boggyb01** [comment]
The log : 
[log.txt](https://github.com/anthonyraymond/joal/files/5179938/log.txt)

**Comment by anthonyraymond** [comment]
hello,

can you send me an unmodified copy of the log file please?
this has been copy pasted in god knows what and it resulted in an unreadable RTF 🤣

**Comment by Boggyb01** [comment]
Hello,

I can only export it in html or csv.
Here is the link to access the html : https://u.pcloud.link/publink/show?code=XZVAs0XZjfNE8O6Q9tVS7eoN8BBDR5Y0lUeV
Thank you

**Comment by anthonyraymond** [comment]
Ok i start to see the problem, as i said in previous message your setup is wrong.

1. Delete `data` and `@eaDir`:
2. Delete `jack-of-all-trades-2.1.21.jar`
3. Run the container with


docker run -d
-p 9000:9000
-v PATH_TO_CONF:/data
--name="joal"
anthonyraymond/joal
--joal-conf="/data"
--spring.main.web-environment=true
--server.port="9000"
--joal.ui.path.prefix="GUIJOAL"
--joal.ui.secret-token="pass"

**Comment by Boggyb01** [comment]
Hello,

Alright, it worked fine. Container is now up and running and once the connection settings are set in the GUI, torrents are seeding.

Thank you
