### ISSUE TITLE
tuto pour raspberry 3B

### ISSUE THREAD

**Issue by Froggonia** [anthonyraymond/joal#106]
Bonjour,
j'essais de configurer Joal via socker sur un Raspberry 3B.
Après avoir tapé la commande "docker pull anthonyraymond/joal" depuis un terminal, je suis un peu perdu .
Je me suis attaqué à : 
_docker run -d \
    -p PORT:PORT \
    -v PATH_TO_CONF:/data \
    --name="joal" \
    anthonyraymond/joal \
    --joal-conf="/data" \
    --spring.main.web-environment=true \
    --server.port="PORT" \
    --joal.ui.path.prefix="SECRET_OBFUSCATION_PATH" \
    --joal.ui.secret-token="SECRET_TOKEN"_

en tapant ceci 

_docker run -d \
    -p 9100:9100 \
    -v joalpath:/data \
    --name="joal" \
    anthonyraymond/joal \
    --joal-conf="/data" \
    --spring.main.web-environment=true \
    --server.port="9100" \
    --joal.ui.path.prefix="joaldesktop" \
    --joal.ui.secret-token="123456789"_

J'ai activé "joal" en "running" depuis "PORTAINER".
Cependant quand je tape l'adresse "localhost:9100/joaldesktop/ui" rien ne se passe .
en joal repasse en "stopped"....

j'ai loupé quelque chose  ?!?

**Comment by anthonyraymond** [comment]
Tu as probablement oublié cette partie: https://github.com/anthonyraymond/joal#1-setting-up-configuration

une fois que ca sera fait remplate ton `joalpath` par le chemin absolue vers ce dossier
