### ISSUE TITLE
Aide avec Traefik et docker-compose

### ISSUE THREAD

**Issue by bxlouis** [anthonyraymond/joal#108]
Bonjour

Je rencontre un problème avec ma configuration utilisant Traefik v2 et docker-compose.
Joal se lance correctement, mais lorsque j'y accède en utilisant l'URL réécrite par Traefik (joal.domain.com), joal ne fonctionne pas et j'obtiens le message d'erreur "FAILED TO CONNECT TO JOAL, RETRY IN 8 SECONDS."
J'ai essayé de modifier les paramètres mais rien n'y fait.

En revanche, dès que je me connecte à joal en utilisant LOCALIP:5081, aucun problème, joal fonctionne parfaitement.
J'aimerais comprendre ce qui coince et éventuellement trouver une solution à mon problème. Pourriez-vous m'aider ?

Voici mon docker-compose : 

> joal:
    restart: unless-stopped
    image: anthonyraymond/joal
    container_name: joal
    networks:
      - t2_proxy
    ports:
      - "$JOAL_PORT:5081"
    volumes:
      - $DOCKERDIR/joal:/data
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=$JOAL_PORT", "--joal.ui.path.prefix=joal", "--joal.ui.secret-token=$JOAL_SECRET"]
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.joal-rtr.entrypoints=https"
      - "traefik.http.routers.joal-rtr.rule=HostHeader(`joal.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.joal-rtr.middlewares=chain-basic-auth@file"
      #- "traefik.http.routers.joal-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.joal-rtr.service=joal-svc"
      - "traefik.http.services.joal-svc.loadbalancer.server.port=5081"

**Comment by bxlouis** [comment]
Après quelques tests et en lisant #33 je comprends qu'il est nécessaire de configurer le reverse proxy pour accepter le web socket, mais je ne suis pas certain de la procédure à suivre avec Traefik.

**Comment by anthonyraymond** [comment]
Je te laisse jetter un oeil au Wiki, tout est expliqué avec Traefik 😉 
https://github.com/anthonyraymond/joal/wiki/Joal-behind-a-reverse-proxy

**Comment by bxlouis** [comment]
Bonjour @anthonyraymond j'ai finalement réussi à faire fonctionner joal derrière Traefik grâce au wiki !
Toutefois, j'ai du indiquer le port "443" dans les connection settings pour que cela fonctionne.

Il y a quand même quelque chose que je ne comprends pas. Le port, le prefix et le token sont passés en "command" dans le docker compose et pourtant, il est toujours nécessaire de renseigner ces informations dans le "connection settings" dès qu'on change de navigateur, qu'on passe en mode incognito ou qu'on vide le cache.
Est-ce bien le comportement voulu ? Si oui, pourquoi ?
Y-a-t-il un moyen de faire persister la configuration?

**Comment by anthonyraymond** [comment]
L'accés à la webui nécessite de connaitre le "prefix", mais il se pourrait que certaines personnent pas trés au point sur la sécuritée utilisent le prefix "joal".
Et si on n'avais pas besoin de retaper les informations de connexions, alors n'importe qui pourrait controller ton JOAL.

Le "prefix" sert a cacher le fait que JOAL tourne chez toi, sans le prefix on ne peut pas voir la webui.
le "secret-token" sert de mot de passe grossièrement.

**Tu est obligé de saisir** ces informations car le serveur et l'UI sont deux composants séparés,
- joal-server: c'est la parti de joal qui gère le seed, etc...
- la webui: ca c'est la partie purement graphique.
 Avec une UI tu peux controller autant de joal-server que tu le souhaite. Il te suffit de connaitre les inforamtions de connexion (host, port, prefix et secret-token). En fait je pourrais heberger sur un serveur la webui et vous pourriez tous utiliser celle ci avec vos informations au lieu de la déployer chez vous en plus du serveur. Mais en france c'est pénible et compliqué a cause des logs, de la confidentialité, de la CNIL, et de tout ce qui s'en suit... Donc à la place, joal-server expose aussi une webui.

Tu dois les **resaisir quand tu vide le cache** car ils sont stockés dans le cache du navigateur.
