### ISSUE TITLE
torrent delete aleatory

### ISSUE THREAD

**Issue by therudy** [anthonyraymond/joal#110]
Hi,

Sorry for my english,

I use joal on raspberry pi and its works fine, i just have a problem :

Aleatory, torrent will be deleted on the joal list, and every  3-4 days, all of torrent will deleted, and need to re-add manually to joal to fake seed again,

"Keep seeding torrents even with no peers" checked or no, its doesnt change anything,

any idea why? 

until this, joal is perfect... thank,

**Comment by anthonyraymond** [comment]
Hi,
it happens when the tracker did not answer more than 2 or 3 times in a row (usually equal to 1h30), if joal fail to contact the tracker for this amount of time it discard all the tracker related torrent.

**Comment by therudy** [comment]
Hi, thank for your reply, 

and i have no issue to fix it? because i need to re-add torrent every 2 days :'(

thank

**Comment by anthonyraymond** [comment]
So far there is not.

But we are actually rewriting the whole app in another language, to make it faster and lighter. the new app won't delete torrent anymore.
But the release is not to be expected in the next few weeks there is still a lot of work to do.
