### ISSUE TITLE
Diviser equitablement l'upload

### ISSUE THREAD

**Issue by chicungunya** [anthonyraymond/joal#111]
Hello,
Saurais tu comment diviser equitablement l'upload ou c'est aléatoire ?
En fait a chaque fois que j'ai plusieurs torrents, c'est généralement 1 qui prend tout.

Voir l'exemple ci-dessous/

Merci ! 

![image](https://user-images.githubusercontent.com/25926287/102937484-450a4f80-4478-11eb-824e-8edc7eff952d.png)

**Comment by anthonyraymond** [comment]
Salut, joal partage uniquement sur les torrents qui ont au moins 1 leecher et 1 seeder, donc c'est pour ca qu'il ne partage pas sur le premier.

La vitesse est repartie automatique en fonction du ratio seed/leech de chaque torrent pour paraître la plus normale possible. Tu ne peux pas le changer
