### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ZEROTT999** [anthonyraymond/joal#116]
Is not a issue a gateway for ace combat cross rumble+ please and keep the hard work

**Comment by anthonyraymond** [comment]
Sorry i don't understand what is it about?

**Comment by ZEROTT999** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by anthonyraymond** [comment]
What do you mean by make codes?

**Comment by ZEROTT999** [comment]
make the ace combat japan version plus

**Comment by anthonyraymond** [comment]
No, i can't rewrite an a random existing game, this is against the law. Event if it was not, it's not possible to create code for 3DS, it's a closed source platform, and event if it was not i would take me way too much time.

Plus i don't know japanese.

**Comment by ZEROTT999** [comment]
and who write the code for ace combat assault horizon legacy plus

**Comment by anthonyraymond** [comment]
I don't know but it's not me.

I don't understand how is this even related to joal.

**Comment by ZEROTT999** [comment]
but in the web you a contribuitor

**Comment by anthonyraymond** [comment]
It might be someone with the same name as me, but i'm not the guy you think i am

**Comment by ZEROTT999** [comment]
Ok thanks anyway


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
