### ISSUE TITLE
Default password for ui access...

### ISSUE THREAD

**Issue by Silvers12** [anthonyraymond/joal#122]
Hi ! 
I have install it with docker with --spring.main.web-environment=true.

When i connect to http://localhost:port/SECRET_OBFUSCATION_PATH/ui/ i arrive on page that ask me User and Password... But i don't know what password it need.
Where can i find this password ? Not in config ... Or i think i'm losing something ^^

Thanks for your future answer ;)

I'm on Debian 10 ;)

Bye !

**Comment by anthonyraymond** [comment]
hum that's weird, can i see a screenshot of the box asking for login / pass ?

**Comment by Silvers12** [comment]
I don't know what i'm doing wrong ....

![image](https://user-images.githubusercontent.com/9714780/106010642-f6288900-60b9-11eb-9954-3452f1711882.png)

**Comment by anthonyraymond** [comment]
well, i don't know what that is but it's not JOAL 😄 

Can you send me:
- The whole **docker run** command
- The config file (json)
- The whole log from the **docker logs**

Send it at joal.contact@gmail.com please :) i'll take a look ASAP.
