### ISSUE TITLE
m[0m[INFO ] 2021-02-01 18:21:28.590 [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats

### ISSUE THREAD

**Issue by Mike-T-Anderson** [anthonyraymond/joal#124]
Getting the following error:

`[m[0m[INFO ] 2021-02-01 18:21:28.590 [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats: WebSocketSession[3 current WS(3)-HttpStream(0)-HttpPoll(0), 4 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(4)-CONNECTED(4)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 64, active threads = 0, queued tasks = 0, completed tasks = 204], outboundChannel[pool size = 38, active threads = 0, queued tasks = 0, completed tasks = 38], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]`

**Comment by anthonyraymond** [comment]
Nous an error

**Comment by Mike-T-Anderson** [comment]
Wow that was lightning fast reply, thanks. I noticed it has stopped uploading but I I have to keep stop and starting it see results.

**Comment by anthonyraymond** [comment]
I'm not sure to understand, what is the problem exactly?
