### ISSUE TITLE
[Feature] Add client libTorrent 0.D.8.0

### ISSUE THREAD

**Issue by CyberPoison** [anthonyraymond/joal#128]
Hi it will be cool to add more clients like the torrents above, if you can please do some wiki to let us do our Clients and push it back to the code here with pull requests it will be awesome.

Thanks

**Comment by anthonyraymond** [comment]
Hello,

@CyberPoison Actually there is already [a wiki](https://github.com/anthonyraymond/joal/wiki/Create-your-own-client-files), but it's somehow outdated now, and most of all i'm working on a newer awesome version. And the client file format a changed quite alot so...

If i were you wouldn't bother too much bout the current version and i'll wait for the new one :). This is not planned anywhere soon though. I still need to code the whole webui (and run some extensive tests on the server part).
