### ISSUE TITLE
Error docker creation

### ISSUE THREAD

**Issue by Dalto1** [anthonyraymond/joal#13]
I got this error when i try to install it via docker :
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"--joal-conf=/data\": stat --joal-conf=/data: no such file or directory".

**Comment by anthonyraymond** [comment]
Hi @Dalto1,
can you send me both of the command you used to create the docker image and running the docker container?

**Comment by Dalto1** [comment]
Voilà
`docker run -d --restart unless-stopped --name="joal" --net=container:openvpn -v /home/joal:/data araymond/joal --joal-conf="/data" --spring.main.web-environment=true --server.port="aport" --joal.ui.path.prefix="something" --joal.ui.secret-token="something"`

**Comment by anthonyraymond** [comment]
Everything looks fine to me expect for the `/home/joal` path, this looks weird (unless you created a joal user), can you send the feddback for `ls /home/joal` please?


<br /><br /><br />
The following sentence is not related to your problem in any way, it's just a warning for openvpn & nginx.
You seems to use a vpn container as a network, which means ou most likely use a nginx as well. The webui uses both http and websocket, here is the required config in nginx:

http confs
```
server {

	...

	location /joal {
	    proxy_pass       http://joal:4242/;
	    proxy_set_header Host $http_host;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Proto $scheme;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header Proxy "";

	    ## Required for websockets
	    proxy_http_version 1.1;
	    proxy_set_header Connection "upgrade";
	    proxy_set_header Upgrade $http_upgrade;
	    proxy_read_timeout 600s;

	    access_log off;
	}
}
```

stream conf
```
server {
    listen YOUR_PORT_HERE;
    proxy_connect_timeout 10s;
    proxy_timeout 1800s;
    proxy_pass aria2:6800;
}

```

**Comment by Dalto1** [comment]
Even this generic settings arent working at all. Same error
`docker run -d \
    -p 7845:7845 \
    -e _JAVA_OPTIONS='-Djava.net.preferIPv6Addresses=true' \
    -v /home/myuserl/docker/joal:/data \
    --name="joal" araymond/joal \
    --joal-conf="/data" \
    --spring.main.web-environment=true \
    --server.port="7845" \
    --joal.ui.path.prefix="saASDqw412wqfas" \
    --joal.ui.secret-token="ASDFA34SDAsafdas5325"`

**Comment by anthonyraymond** [comment]
it's weird, it is working flawlessly on both my ubuntu x64 and raspberry (using respective dockerfiles).

Would you mind trying deleteing everything?

`docker stop joal`
`docker rm joal`
`docker rmi araymond/joal`

then creating again
`docker build -f Dockerfile -t araymond/joal .`  (if you are using a raspberry replace Dockerfile with Dockerfile.arm)

```
docker run -d \
    -p 7845:7845 \
    -e _JAVA_OPTIONS='-Djava.net.preferIPv6Addresses=true' \
    -v /home/myuserl/docker/joal:/data \
    --name="joal" araymond/joal \
    --joal-conf="/data" \
    --spring.main.web-environment=true \
    --server.port="7845" \
    --joal.ui.path.prefix="saASDqw412wqfas" \
    --joal.ui.secret-token="ASDFA34SDAsafdas5325"
```

I recommend copy pasting directly to the console, your bug may be related to a CRLF issue if you are using a shell script to start JOAL.

**Comment by Dalto1** [comment]
the command 
docker build -f Dockerfile -t araymond/joal
is doing this
`"docker build" requires exactly 1 argument.
See 'docker build --help'.
Usage:  docker build [OPTIONS] PATH | URL | -
Build an image from a Dockerfile`

however with this command, i can acheive something but same result at the end
`docker build -t araymond/joal /home/gabriel/docker/joal-2.0.5`

`docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"--joal-conf=/data\": stat --joal-conf=/data: no such file or directory".`

**Comment by anthonyraymond** [comment]
You forgot the "." At the end of the docker buils command.

Have you copy pasted the run command in a terminal or did you start the container with a shell script?

**Comment by Dalto1** [comment]
Im trying this exact commands and it doesnt work :

wget https://github.com/anthonyraymond/joal/archive/v2.0.5.zip
unzip v2.0.5.zip -d /home/myuser/docker/
cd /home/myuser/docker/joal-2.0.5
docker build -f Dockerfile -t araymond/joal .

mkdir -p /home/myuser/docker/joal
docker run -d \
    -p 7845:7845 \
    -e _JAVA_OPTIONS='-Djava.net.preferIPv6Addresses=false' \
    -v /home/myuser/docker/joal:/data \
    --name="joal" araymond/joal \
    --joal-conf="/data" \
    --spring.main.web-environment=true \
    --server.port="7845" \
    --joal.ui.path.prefix="ASFqwt1q35qwe5asdf" \
    --joal.ui.secret-token="AFS31q5135dasas5"	

I can see this
`The command '/bin/sh -c apt-get update         && apt-get install -y ca-certificates curl         && curl -s https://api.github.com/repos/anthonyraymond/joal/releases/latest         | grep browser_download_url         | grep joal.tar.gz         | cut -d '"' -f 4         | wget -i -         && tar --wildcards -zxvf joal.tar.gz '*.jar'         && mv *.jar joal.jar         && rm joal.tar.gz         && apt-get remove curl         && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1`

and this in the command lines
`debconf: delaying package configuration, since apt-utils is not installed`

**Comment by anthonyraymond** [comment]
About the `debconf: delaying package configuration, since apt-utils is not installed` there no need to worry.

I've updated both of the Dockerfile on github yesterday, try downloading the archive from [here](https://github.com/anthonyraymond/joal/archive/master.zip) instead.

Also be sur you use the correct Dockerfile:
For regular **x86/x64** linux use `docker build -f Dockerfile -t araymond/joal .`
For **arm** (raspberry) use `docker build -f Dockerfile -t araymond/joal .`

Then :
```
docker run -d \
    -p 7845:7845 \
    -e _JAVA_OPTIONS='-Djava.net.preferIPv6Addresses=true' \
    -v /home/myuserl/docker/joal:/data \
    --name="joal" araymond/joal \
    --joal-conf="/data" \
    --spring.main.web-environment=true \
    --server.port="7845" \
    --joal.ui.path.prefix="saASDqw412wqfas" \
    --joal.ui.secret-token="ASDFA34SDAsafdas5325"
```

**Comment by Dalto1** [comment]
worked with the last update thanks
