### ISSUE TITLE
[ygg] No upload detected

### ISSUE THREAD

**Issue by HpNoTiQ56** [anthonyraymond/joal#131]
System : latest Joal docker on unraid though Wireguard VPN.

Problem : been uploading with 3-4 torrents since 2 days and my ratio isn't going up.
I tried to switch to other client (tried qbittorrent, vuze) with no sucess.

No problem in logs 
`ErrorWarningSystemArrayLogin

The.Queens.Gambit.S01.MULTI.2160p.10bit.4KLight.HDR.BluRay.x265.E-AC3-BONBON
[m[0m[INFO ] 2021-04-07 22:01:28.030 [ main] c.t.t.c.Torrent: Announced at:
[m[0m[INFO ] 2021-04-07 22:01:28.030 [ main] c.t.t.c.Torrent: 1. http://connect.p2p-tracker.net:8080/*****/announce
[m[0m[INFO ] 2021-04-07 22:01:28.030 [ main] c.t.t.c.Torrent: Created on..: 2021-04-06T08:22:42.000+0200
[m[0m[INFO ] 2021-04-07 22:01:28.030 [ main] c.t.t.c.Torrent: Created by..: YggTorrent
[m[0m[INFO ] 2021-04-07 22:01:28.030 [ main] c.t.t.c.Torrent: Found 7 file(s) in multi-file torrent structure.
[m[0m[INFO ] 2021-04-07 22:01:28.030 [ main] c.t.t.c.Torrent: Pieces......: 6565 piece(s) (2097152 byte(s)/piece)
[m[0m[INFO ] 2021-04-07 22:01:28.030 [ main] c.t.t.c.Torrent: Total size..: 13,765,995,045 byte(s)
[m[0m[INFO ] 2021-04-07 22:01:28.030 [ main] o.a.j.c.t.w.TorrentFileProvider: Torrent file addition detected, hot creating file: /data/torrents/Shingeki.no.Kyojin.S04.ENGLISH.1080p.WEB.x264-RiPiT (L'Attaque des Titans Saison Finale).torrent
[m[0m[INFO ] 2021-04-07 22:01:28.032 [ main] c.t.t.c.Torrent: Multi-file torrent information:
[m[0m[INFO ] 2021-04-07 22:01:28.032 [ main] c.t.t.c.Torrent: Torrent name: Shingeki No Kyojin Saison Finale
[m[0m[INFO ] 2021-04-07 22:01:28.032 [ main] c.t.t.c.Torrent: Announced at:
[m[0m[INFO ] 2021-04-07 22:01:28.032 [ main] c.t.t.c.Torrent: 1. http://connect.p2p-tracker.net:8080/*****/announce
[m[0m[INFO ] 2021-04-07 22:01:28.032 [ main] c.t.t.c.Torrent: Created on..: 2021-04-06T08:33:57.000+0200
[m[0m[INFO ] 2021-04-07 22:01:28.032 [ main] c.t.t.c.Torrent: Created by..: YggTorrent
[m[0m[INFO ] 2021-04-07 22:01:28.032 [ main] c.t.t.c.Torrent: Found 17 file(s) in multi-file torrent structure.
[m[0m[INFO ] 2021-04-07 22:01:28.033 [ main] c.t.t.c.Torrent: Pieces......: 1447 piece(s) (8388608 byte(s)/piece)
[m[0m[INFO ] 2021-04-07 22:01:28.033 [ main] c.t.t.c.Torrent: Total size..: 12,130,104,943 byte(s)
[m[0m[INFO ] 2021-04-07 22:01:28.084 [ main] o.a.j.c.c.JoalConfigProvider: App configuration has been successfully loaded.
[m[0m[INFO ] 2021-04-07 22:01:28.397 [ annnouncer-0] o.a.j.c.t.c.a.Announcer: 9×È¸Èn»WGKK¼àut has announced successfully. Response: 6 seeders, 0 leechers, 1800s interval
[m[0m[INFO ] 2021-04-07 22:01:28.397 [ annnouncer-2] o.a.j.c.t.c.a.Announcer: Z-Îä¡ÉtÖKWúÅ&Þ`<" has announced successfully. Response: 165 seeders, 1 leechers, 1800s interval
[m[0m[INFO ] 2021-04-07 22:01:28.397 [ annnouncer-1] o.a.j.c.t.c.a.Announcer: ±ÌÍAô¤Ï¥ÓÍzEìáá/ÛÝ«÷ has announced successfully. Response: 48 seeders, 1 leechers, 1800s interval
[m[0m[INFO ] 2021-04-07 22:01:28.511 [ annnouncer-0] o.a.j.c.t.c.a.Announcer: -.ènÁØà½³Æz©AÚ>y has announced successfully. Response: 38 seeders, 1 leechers, 1800s interval
[m[0m[INFO ] 2021-04-07 22:01:28.512 [ annnouncer-1] o.a.j.c.t.c.a.Announcer: ÙU@b-Â]#Máª§ð{Ç has announced successfully. Response: 276 seeders, 39 leechers, 1800s interval
[m[0m[INFO ] 2021-04-07 22:01:33.355 [http-nio-5656-exec-1] o.a.c.c.C.[.[.[/]: Initializing Spring DispatcherServlet 'joal'
[m[0m[INFO ] 2021-04-07 22:01:33.355 [http-nio-5656-exec-1] o.s.w.s.DispatcherServlet: Initializing Servlet 'joal'
[m[0m[INFO ] 2021-04-07 22:01:33.363 [http-nio-5656-exec-1] o.s.w.s.DispatcherServlet: Completed initialization in 8 ms
[m[0m[INFO ] 2021-04-07 22:02:27.438 [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats: WebSocketSession[1 current WS(1)-HttpStream(0)-HttpPoll(0), 1 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(1)-CONNECTED(1)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 12, active threads = 0, queued tasks = 0, completed tasks = 27], outboundChannel[pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 2], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]

[m[0m[INFO ] 2021-04-07 22:31:28.665 [ annnouncer-1] o.a.j.c.t.c.a.Announcer: 9×È¸Èn»WGKK¼àut has announced successfully. Response: 6 seeders, 0 leechers, 1800s interval
[m[0m[INFO ] 2021-04-07 22:31:28.665 [ annnouncer-0] o.a.j.c.t.c.a.Announcer: ±ÌÍAô¤Ï¥ÓÍzEìáá/ÛÝ«÷ has announced successfully. Response: 50 seeders, 1 leechers, 1800s interval
[m[0m[INFO ] 2021-04-07 22:31:28.665 [ annnouncer-2] o.a.j.c.t.c.a.Announcer: Z-Îä¡ÉtÖKWúÅ&Þ`<" has announced successfully. Response: 166 seeders, 0 leechers, 1800s interval
[m[0m[INFO ] 2021-04-07 22:31:29.590 [ annnouncer-1] o.a.j.c.t.c.a.Announcer: -.ènÁØà½³Æz©AÚ>y has announced successfully. Response: 38 seeders, 1 leechers, 1800s interval
[m[0m[INFO ] 2021-04-07 22:31:29.591 [ annnouncer-2] o.a.j.c.t.c.a.Announcer: ÙU@b-Â]#Máª§ð{Ç has announced successfully. Response: 271 seeders, 41 leechers, 1800s interval
[m[0m[INFO ] 2021-04-07 22:32:27.438 [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats: WebSocketSession[1 current WS(1)-HttpStream(0)-HttpPoll(0), 1 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(1)-CONNECTED(1)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 12, active threads = 0, queued tasks = 0, completed tasks = 75], outboundChannel[pool size = 12, active threads = 0, queued tasks = 0, completed tasks = 18], sockJsScheduler[pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 1]
`

**Comment by anthonyraymond** [comment]
in the log you sent, i can see one torrent with both seeder and leechers. Under this circumstances JOAL must produce data and send it to the tracker.

Running JOAL is almost like running a real client (except that you can choose the amount of data send to the tracker). But using JOAL for 30min won't give you ratio a +10% boost.

If your current ratio is : 1 with (500Go Upload and 500Go Download) uploading 500Mo with joal won't make such a difference compared to the 500Go, the change will be so small that it is actually rounded, if you had acces to all the decimal your ratio would look like 1.01 Ratio or so.

You need to leave JOAL running for a fair amout of time to actually see the benefits. I do run mine 24/7 at low speed (between 0 and 50Ko/s) and i don't have to think about my ratio anymore.
