### ISSUE TITLE
Hi, I've done an addon for HA

### ISSUE THREAD

**Issue by alexbelgium** [anthonyraymond/joal#134]
Hi, 

I've done an addon for Home Assistant (https://www.home-assistant.io) based on your docker image.
It is a very popular automation platform also used for self hosting.

If you are interested to tell about it in your README as an installation method, here is the github repo of the addon : https://github.com/alexbelgium/hassio-addons/tree/master/joal
I've included a screenshot of how it looks in the HA app.

Btw, thanks very much for this app this works great!

Best regards,
Alexandre

**Comment by anthonyraymond** [comment]
Hi @alexbelgium 

Looks good to me, I like the idea.

Two questions though:
 - can you move the 2.1.4 version number in run.sh somewhere else? perhaps as an environment variable defined in the Dockerfile?
 - When the v2 gets release, will you update your addon ?

**Comment by alexbelgium** [comment]
Hi @anthonyraymond,
Great, thanks for the feedback! Your right about hard coding the version number (2.1.24), I'll link it to the addon version. HA triggers the update of addons on user systems based on a modification if the addon version number, so anyway the addon version must be updated for each new upstream versions. 

I've got a script for all my addons that checks daily upstream repos (such as yours) for new releases, and align the addons automatically. Of course I double check in case of major versions - so I'll gladly implement the next version you are developing.

Best regards,
Alexbelgium

**Comment by alexbelgium** [comment]
The run.sh code is upgraded to always download the latest release, without specifying a version.

Only wip is enabling nginx from an external network (currently only works with internal), but I saw the thread in a closed issue describing that so it should be a matter of days

I've also added an option to auto stop Joal after a predefined amount of time (to avoid overshooting ratio)

**Comment by anthonyraymond** [comment]
Looks good to me, can the user still change the secret token and path prefix?

**Comment by alexbelgium** [comment]
I've hard coded the prefix for the moment to simplify accessing the webui, but the secret token can be modified from the addon option. Users receive a warning if they kept the default one (lrMY24Byhx)

I could allow to change the prefix and modify the nginx files at boot with a bash script however this means HA won't be able to provide the working url from its interface.

A halfway solution could be that I allow the path to be changed as an option - getting better security while losing some convenience.

**Comment by alexbelgium** [comment]
Ok, optional setting of custom path is implemented as an option ;)

**Comment by alexbelgium** [comment]
Implementing Ingress seems complex... It is not required for using it in Home Assistant, but would be a nice added value to my addon as it avoids exposing Joal port externally. 

The HA ingress system based on nginx works like this : 
We connect to the main app with http://servername.fr:8123, which is the only externally exposed port. From within the app, we click on the addon button which go to an url such as http://servername.fr:8123/api/hassio_ingress/2heybeu3h37hyhj743jj7e/

When we go at this address, Home Assistant redirects the request to a virtual port open in the addon, 8099, at which nginx listens and forwards the request to the upstream http://127.0.0.1:8081/joal/ui

In parallel, docker also exposes http://127.0.0.1:8081 to http://LOCALIP:8091. 

To summarize, we can access the addon with a direct link from http://LOCALIP:8091/joal/ui, or with an indirect one with http://servername.fr:8123/api/hassio_ingress/2heybeu3h37h3jj7e/

My main issue is the websocket authentification. I can connect on my local network by bypassing nginx, and connecting directly by typing the server "LOCALIP", port "8091", and my path and secret key.

Of course, outside my home it doesn't work as this port isn't exposed. I tried to connect by encoding "http://servername.fr:8123/api/hassio_ingress/2heybeu3h37h3jj7e/" as server, and 8123 as port, but it fails as the websocket tries to connect to ws://servername.fr:8123

Any idea what I should do? My nginx configuration is here : https://github.com/alexbelgium/hassio-addons/tree/master/joal/rootfs/etc/nginx

Thanks very much! If it can't work its no bother, a lot of addons don't have Ingress and are still highly used in the HA community

**Comment by anthonyraymond** [comment]
my concern was more about the fact that the `path-prefix` and `secret-token` was both using fixed values. That's not good because it let people know you are running JOAL (unless the 2heybeu3h3h37h3... part is a random part different for every people?)

Also, is there a way for the user of your HA addon to access the configuration file? So far there is not much, but the v2 will me much more configurable and there are plenty of config files.

I don't know how nginx works in HA but if you want to take a look this topic is discussing and solving issue people encounter with nginx: https://github.com/anthonyraymond/joal/issues/33

**Comment by alexbelgium** [comment]
Hi, yes the config file can be made available to all, I just need to do a symlink between the config file ikn /data (default mount point of the addon volume) and /config/joal, the /config folder being accessible both from the interface with a text editor or with smb.

Thanks for the nginx tips, I'll look at how to map both endpoints.

**Comment by alexbelgium** [comment]
Hi, OK it's done, config.json is exposed in a /config/joal folders accessible from the HA interface or with smb for direct access

**Comment by alexbelgium** [comment]
Hi, and ingress now works thanks for the pointer of having a specific endpoint for websocket. I've added the instructions in the readme.

**Comment by anthonyraymond** [comment]
👍 Looks great to me. I just updated the REAME to mention your project
![image](https://user-images.githubusercontent.com/7503585/119158706-caf5eb00-ba56-11eb-875e-f3aa0a90402e.png)

The readme is a bit hugly atm... But i plan to rework it for the V2.

Not sure what you mean by "pre-encoding" the server & port. Do you mean to fill the form that asks for host / port / credentials?
If so there is a way that i don't recommend ^^. i actually use that for the desktop app version:

1. This is how to call the uri (with url query param): https://github.com/anthonyraymond/joal-desktop/blob/master/app/electron/WindowManager.js#L105

With uiConfig being an object like: 
```
{
    host: string,
    port: number,
    pathPrefix: string,
    secretToken: string
}
```

But to be honest this is not battlefield tested... V2 will be much more stable on this subject.

**Comment by alexbelgium** [comment]
That's perfect, thanks ! For the moment probably leave things as such (manual encoding of the form), and provide detailed explanations on how to get the info to make it work with HA internal structure. But good to know it exists :-)

I'll close the topic, thanks.
