### ISSUE TITLE
Openvpn

### ISSUE THREAD

**Issue by Dalto1** [anthonyraymond/joal#14]
Dont know if it is because im running joal into a openvpn net container, but the UI cant connect to the backend.

`FAILED TO CONNECT TO JOAL, RETRY IN 8 SECONDS.`

I use the `--net=container:openvpn` argument when launching the docker container

**Comment by anthonyraymond** [comment]
There might be multiple reasons to this issue:

1) Have you filled correctly the connections settings (the top left red button on joal ui)
2) Can you send me the full docker run command for your VPN container?
3) Do you use nginx as a reverse proxy?

**Comment by Dalto1** [comment]
My bad i missed the big red button hahahahah :1st_place_medal:

**Comment by anthonyraymond** [comment]
Haha

**Comment by arthur-ehrle** [comment]
Thank's bros, 8 years later this disscussion saved me beause I got the exact same issue  !
