### ISSUE TITLE
This kind of tracker address is not supported?

### ISSUE THREAD

**Issue by XYC-EXP** [anthonyraymond/joal#140]
### https://aaa.bbb.cccc/announce.php?authkey=9207|885|AJ2uIk80

**Comment by anthonyraymond** [comment]
It is supported, why wouldn't it be? What is the problem?

**Comment by bingyu50** [comment]
but I got that error: "TORRENT WAS REJECTED BY SERVER: JAVA.NET.URISYNTAXEXCEPTION: ILLEGAL CHARACTER IN QUERY AT INDEX 48: " for all this kind of tracker address

**Comment by imswel** [comment]
I got the same error "TORRENT WAS REJECTED BY SERVER: JAVA.NET.URISYNTAXEXCEPTION: ILLEGAL CHARACTER IN QUERY AT INDEX 48: "

**Comment by anthonyraymond** [comment]
Duplicate of #171
