### ISSUE TITLE
torrent protocol port ?

### ISSUE THREAD

**Issue by Cissoubaka** [anthonyraymond/joal#141]
Is it possible to configure a specific port for the torrent protocol ?

**Comment by anthonyraymond** [comment]
With the current version, no you can't. But i'm currently rewriting the app in another language and that is alwready something that you can do. But there is still a lot of work to be done before the new version comes out.

**Comment by mohitjoshi155** [comment]
any updates on this?

**Comment by rursache** [comment]
@anthonyraymond any update on this? it seems it seeds on port 49152

**Comment by anthonyraymond** [comment]
Still working on rewriting the app
