### ISSUE TITLE
Torrents folder not found

### ISSUE THREAD

**Issue by yaoberh** [anthonyraymond/joal#145]
Hey!
Don't know if I'm doing anything wrong but I get an error right after launching joal.
Tried moving the config file, put it in a subfolder but even so it doesn't seem to detect the torrents folder. Error is:
`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.araymond.joal.core.SeedManager]: Factory method 'seedManager' threw exception; nested exception is java.io.FileNotFoundException: Torrent folder '/home/yaoberh/joal/config/config.json/torrents' not found.`

**Comment by anthonyraymond** [comment]
can i see the command you use to start joal?

**Comment by yaoberh** [comment]
`java -jar jack-of-all-trades-2.1.26.jar --joal-conf="/home/yaoberh/joal/config/config.json"`

**Comment by anthonyraymond** [comment]
Try with `java -jar jack-of-all-trades-2.1.26.jar --joal-conf="/home/yaoberh/joal/config/"`

The expected path is the path to the config folder, not the json file itself.
