### ISSUE TITLE
La vitesse reste à 0

### ISSUE THREAD

**Issue by chicungunya** [anthonyraymond/joal#147]
Salut,
Est-ce que certains trackers privés bloque Joal ? 
J'ai essayé 2 torrents avec  au moins 10 seeders et 10 leechers sur CrazyHD et HD-Torrents mais la vitesse reste à 0.
Avec YGG, IPT et TL ca fonctionne.
Je fais quelque chose qui ne va pas ? 
![image](https://user-images.githubusercontent.com/25926287/141497208-064b641e-fdf9-4c29-aadd-db6a5a1b9c73.png)

joal 2.1.26
Raspberry pi 4
Docker

Merci !

**Comment by anthonyraymond** [comment]
Joal ne génère de l'uplaod que si il y a au moins 1 seeder ET 1 leechers, je vois que tes deux torrents ont 0 seed et 0 leech donc c'est normal que la vitesse reste à 0.

Par contre, il se peut que JOAL detecte 0 seed & leech alros qu'en fait il y en a. C'est un problème qui sera regler avec la V3 (mais il rest eencore pas ma lde chemin avant que ca soit prêt). C'est un problème que j'ai identifié mais qui est compliqué a reglé avec la facon dont c'est codé actuellement. Sur certain tracker il ne detecte pas bien les peers.

**Comment by chicungunya** [comment]
Merci pour ta reponse et d'avoir enlevé ma ligne de code.
Justement j'ai laissé tourné mais dans mon profil sur CrazyHD Hd-torrents, le ratio ne bouge pas du tout en upload.. Donc je pense que ca ne fonctionne pas du tout. Il y a vraiment des seeders et des leechers.

**Comment by anthonyraymond** [comment]
Alors il fait parti des quelque tracker pour lesquels JOAL n'arrive pas a identifier les peers.
Ca sera reglé en V3, mais il me reste pas mal de choses a développer encore avant de pouvoir sortir la version définitive.

**Comment by chicungunya** [comment]
All right ! Merci pour les précisions :)
