### ISSUE TITLE
How  does this thing work???

### ISSUE THREAD

**Issue by val3riefr** [anthonyraymond/joal#148]
Ok i've read the info, but it's impossible to understand when you don't know anything about code and stuff...I mean Java, Docker ... ??

I'm on a mac i need to get my ratio higher on a certain torrent site, what should i do? i put one torrent file into the joal program but it doesn't seem to do anything..?
it's says 0 / Bs by the trashcan
a video tutorial would be great to help set up this...

**Comment by anthonyraymond** [comment]
If it says 0 B/s it meand that the torrent you are using have 0 leecher OR 0 seeder, find a more active torrent

Le 13 nov. 2021, 12:49, à 12:49, val3riefr ***@***.***> a écrit:

**Comment by val3riefr** [comment]
i don't have any unfortunately :( 
i thought the program was to higher the ratio? so you obligatorily need leecher to make it work?

**Comment by anthonyraymond** [comment]
Leechers and seeders, it wouls look suspicious if yiu were generating upload on a torrent that nobody asks for.
Just download an active torrent from your tracker

**Comment by val3riefr** [comment]
but they have seeders so it's strange..
and i need to have the file of the torrent on my computer to make it work?

**Comment by anthonyraymond** [comment]
Having seeder does not mean they are seeding at the moment. They are waiting dor somebody to ask.

You juste need the .torrent file, not to download the whole think

**Comment by val3riefr** [comment]
so does this work? my ratio is not moving on the website
<img width="1008" alt="Capture d’écran 2021-11-13 à 13 23 20" src="https://user-images.githubusercontent.com/71612355/141643660-a248d117-ff80-4887-9424-f69d69f8add7.png">
k?

**Comment by val3riefr** [comment]
can the speed be higer? it's says Overall speed  118 kb/s
i won't get my ratio back with that speed...

**Comment by val3riefr** [comment]
it worked perfectly!! thank you so much! now my ratio is back on track
