### ISSUE TITLE
Reverse proxy with Nginx proxy manager

### ISSUE THREAD

**Issue by chicungunya** [anthonyraymond/joal#149]
Hi,
I'm using nginx proxy manager for all my docker containers.
I try to do the same with joal but it can't connect.
Below my settings : 
![joal1](https://user-images.githubusercontent.com/25926287/142477512-793532bd-4914-4dec-8c26-a7fd1a68eb31.jpg)
![image](https://user-images.githubusercontent.com/25926287/142477531-60958852-a195-43cd-bd4b-b961826d46d3.png)
![joal2](https://user-images.githubusercontent.com/25926287/142477629-3919af63-670c-413d-ba5f-2f67adfef482.jpg)
![image](https://user-images.githubusercontent.com/25926287/142477651-e154e63d-094b-4990-ac40-e2e4c113f5d7.png)

When i go to https://myserver/my path prefix/ui/#/, I can't connect  : 

![joal3](https://user-images.githubusercontent.com/25926287/142477970-926d6f0e-1aef-48af-bbbc-29bd6c357017.jpg)

tried with 80, 443 and 8080 (local port)
Using joal with raspberry 4 with docker and portainer.

Thanks a lot!

**Comment by anthonyraymond** [comment]
Hello,

Long story short: you need to allow WebSocket in the nginx as weel as http: see https://github.com/anthonyraymond/joal/issues/33


But i would definely advise you to let go on nginx and make the switch to traefik: a full how to guide to set up VPN + joal + reverse proxy (traefik) [here](https://github.com/anthonyraymond/joal/wiki/Joal-&-VPN-&-qbittorrent-&-Reverse-proxy-(with-docker))
