### ISSUE TITLE
What would it take to run under JDK 11?

### ISSUE THREAD

**Issue by sleaze** [anthonyraymond/joal#150]
Hi @anthonyraymond,

First, thanks so much making JOAL, it's an amazing project!

Do you happen to know what would be required to get it working under a newer version of Java?  Really curious to learn if it'd scale better under GraalVM JDK11.

Thanks again,
SD

**Comment by sleaze** [comment]
Nevermind, it works great under JDK 11 already :D

**Comment by anthonyraymond** [comment]
Indeed it works, actually the latests desktop version runs on JDK11 as well as Docker releases
