### ISSUE TITLE
UI stuck looping

### ISSUE THREAD

**Issue by rgarrigue** [anthonyraymond/joal#155]
Hi there

I made a quick compose based joal setup, just so I can drop a couple of torrent files & run it locally to bring my ratio up. Compose logs are fine, but the UI tabs are spinning endlessly. The browser console says

> error message from websocket 
close { target: WebSocket, isTrusted: true, wasClean: true, code: 1006, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
JoalStompClient.ts:81:14

Tried with latest & pinning latest release. Docker's Ubuntu 21.10 latest, `Docker version 20.10.12, build e91ed57`.
Here's my conf, you should be able to reproduce just running docker-compose up -d https://github.com/rgarrigue/joal-conf

**Comment by rgarrigue** [comment]
Well, it started working at some point, dunno how or why really. Maybe because I edited the connection settings, didnt worked out immediatly but after some time ... ? Here's a maybe interesting line in the logs

> joal    | [INFO ] 2022-02-09 11:19:54.294 [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats: WebSocketSession[1 current WS(1)-HttpStream(0)-HttpPoll(0), 1 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(1)-CONNECTED(1)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 9, active threads = 0, queued tasks = 0, completed tasks = 39], outboundChannel[pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 6], sockJsScheduler[pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 1]

**Comment by anthonyraymond** [comment]
The error means that the websocket client (from browser) fails to connect to the server (using details you set in "connection settings").

Most of the time it's an error in the connections details.

Glad to hear it works
