### ISSUE TITLE
Seed time

### ISSUE THREAD

**Issue by mohitjoshi155** [anthonyraymond/joal#159]
It would be awesome if it also showed how long it has been seeding for

**Comment by anthonyraymond** [comment]
That's already planned for the future version that i am rewriting from scratch. It won't be available on release but i will definely implement that.

**Comment by clementmoine** [comment]
That would be awesome to prevent Hit&Run system to tell you that you stole the content ^^ Just seeding from no download trigger the Hit&Run system if you are not seeding 72h / 48h or so depending on the tracker rules about Hit&Run. Some don't trigger the Hit&Run if you didn't download and just seeding but some do :O
