### ISSUE TITLE
keepTorrentWithZeroSeeders

### ISSUE THREAD

**Issue by mohitjoshi155** [anthonyraymond/joal#161]
Just like keepTorrentWithZeroLeechers there should be a reverse keepTorrentWithZeroSeeders option that removes torrent on 0 seeders

**Comment by anthonyraymond** [comment]
I'm rewritign the app and i've changed the way it work quite a bit, this option has disapeared as it was not intuitive to most of the users.
The new version of the app is not ready yet, i still have a large amount of work to do before releasing it.
