### ISSUE TITLE
Ansible role to install joal

### ISSUE THREAD

**Issue by slundi** [anthonyraymond/joal#162]
Hi,

I've made a little Ansible role to install JOAL, you can try it here :
- https://github.com/slundi/ansible-joal
- https://galaxy.ansible.com/slundi/ansible_joal

Can you add the Ansible install steps in README.md above or bellow Docker install?

Regards

**Comment by anthonyraymond** [comment]
Wow sick!
Thanks a lot for that, i've just added a link to your Ansible role to the [Community projects] (https://github.com/anthonyraymond/joal/blob/master/README.md#community-projects) chapter !
