### ISSUE TITLE
Can't add torrent - Tracker message violates expected protocol

### ISSUE THREAD

**Issue by Ruchamimi** [anthonyraymond/joal#175]
I can't add torrent from french semi-private tracker YGGtorrents. It is directly moved to archived folder. From logs, I see an error "Tracker message violates expected protocol" (see full log below). Is this a protection that the tracker have found?

This setup has worked with the same tracker a few month before.

> [WARN ] 2022-10-23 17:21:17.511 [   annnouncer-1] o.a.j.c.t.c.a.t.TrackerResponseHandler: Tracker response is an error.

> [WARN ] 2022-10-23 17:21:17.513 [   annnouncer-1] o.a.j.c.t.c.a.Announcer: `NZîæ00K&:UáTÈ¹ÐG¹ has failed to announce

> com.turn.ttorrent.client.announce.AnnounceException:` Failed to handle tracker response: Tracker message violates expected protocol (Could not decode tracker message (not B-encoded?)!)
> 	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:66)
> 	at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:64)
> 	at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40)
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: com.turn.ttorrent.client.announce.AnnounceException: Failed to handle tracker response: Tracker message violates expected protocol (Could not decode tracker message (not B-encoded?)!)
> 	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:108)
> 	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.announce(TrackerClient.java:53)
> 	... 6 more
> Caused by: java.io.IOException: Tracker message violates expected protocol (Could not decode tracker message (not B-encoded?)!)
> 	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerResponseHandler.handleResponse(TrackerResponseHandler.java:49)
> 	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerResponseHandler.handleResponse(TrackerResponseHandler.java:17)
> 	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.handleResponse(TrackerClient.java:114)
> 	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerClient.makeCallAndGetResponseAsByteBuffer(TrackerClient.java:106)
> 	... 7 more
> Caused by: com.turn.ttorrent.client.announce.AnnounceException: Tracker message violates expected protocol (Could not decode tracker message (not B-encoded?)!)
> 	... 11 more
> Caused by: com.turn.ttorrent.common.protocol.TrackerMessage$MessageValidationException: Could not decode tracker message (not B-encoded?)!
> 	at com.turn.ttorrent.common.protocol.http.HTTPTrackerMessage.parse(HTTPTrackerMessage.java:42)
> 	at org.araymond.joal.core.ttorrent.client.announcer.tracker.TrackerResponseHandler.handleResponse(TrackerResponseHandler.java:43)
> 	... 10 more
> [INFO ] 2022-10-23 17:21:17.517 [   annnouncer-1] o.a.j.c.t.c.a.Announcer: `NZîæ00K&:UáTÈ¹ÐG¹ has failed to announce 5 times in a raw
> [INFO ] 2022-10-23 17:21:17.546 [   annnouncer-1] o.a.j.c.t.w.TorrentFileProvider: Torrent file deleting detected, hot deleted file: /data/torrents/Microsoft Office 2019 Professional Plus 2003 Build 12624.20520.torrent
> [INFO ] 2022-10-23 17:21:17.568 [   annnouncer-1] o.a.j.c.t.w.TorrentFileProvider: Successfully moved file: /data/torrents/Microsoft Office 2019 Professional Plus 2003 Build 12624.20520.torrent to archive folder
> `

**Comment by anthonyraymond** [comment]
Maybe the torrent file points toward the old tracker address. Or maybe access to YGG is blocked by your ISP?
Or maybe you set an unrealistic speed in configuration and you've been banned?

Does it work with other torrents from the same tracker ? Try to download a fresh torrent from your tracker instead of using .torrent file you already have in your downloads. From time to time this particular tracker seems to change their domain in the .torrent files.

**Comment by Ruchamimi** [comment]
Hello ! It has the same behavior with old and freshly downloaded Torrent.
It doesn't seem I'm banned as this account is still active with *arr
ecosystem, will try manual download this evening. I don't think I'm ISP
blocked as I use custom DNS for downloading torrent with *arr.

Do you want me to send a torrent file ? I can create a dummy account, check
if the error happens, and send the Torrent file to you if you would like to.

Marc

Le mer. 2 nov. 2022, 13:31, Anthony Raymond ***@***.***> a
écrit :

**Comment by anthonyraymond** [comment]
Torrent won't be needed, we'll find a way around to get the error from the tracker. But i'd like to know if the manual download works.

Is JOAL running in Docker?

**Comment by Ruchamimi** [comment]
I have been able to manually download a file successfully just now. Same torrent doesn't open in Joal. It runs in Docker, last released version.

**Comment by Ruchamimi** [comment]
I have just tried again. I can still manually download torrent with my account, but joal cannot connect to the Torrent. Is ygg working with other users ?

**Comment by Ruchamimi** [comment]
New info on this bug : Joal desktop version (on windows) works, and not the docker version on my raspberry pi. I tried reinstalling everything on docker with no success. I used the same torrent.

**Comment by anthonyraymond** [comment]
That's weird, they run the same joal program with th eexact same version.
Can you show me how you start your docker container? The docker run command or docker compose file please.

**Comment by Ruchamimi** [comment]
I didn't change much from the instructions :

`docker run -d \
    -p 1900:1900 \
    -v /home/pi/Joal-conf:/data \
    --name="joal" \
    anthonyraymond/joal:latest \
    --joal-conf="/data" \
    --spring.main.web-environment=true \
    --server.port="1900" \
    --joal.ui.path.prefix="salutcestcool" \
    --joal.ui.secret-token="francmacons"`

**Comment by Ruchamimi** [comment]
Thanks, I didn't know! I thought by doing a docker pull it was using the latest, see my images : 
` 
 pi@raspberrypi:~ $ docker images
 REPOSITORY                  TAG       IMAGE ID       CREATED         SIZE
 containrrr/watchtower       latest    09b618784c4b   2 weeks ago     13.9MB
 flaresolverr/flaresolverr   latest    c51a7bad8d01   5 weeks ago     443MB
 anthonyraymond/joal         latest    6c0677bc708a   2 months ago    260MB
 anthonyraymond/joal         <none>    ad6e4418b812   13 months ago   258MB
'

Anyway, I did a `docker rm joal` and then 

`
docker run -d \
-p 1900:1900 \
-v /home/pi/Joal-conf:/data \
--name="joal" \
anthonyraymond/joal:2.1.33 \
--joal-conf="/data" \
--spring.main.web-environment=true \
--server.port="1900" \
--joal.ui.path.prefix="salutcestcool" \
--joal.ui.secret-token="francmacons"`
`

That doesn't solve the issue :c

**Comment by anthonyraymond** [comment]
Well it's not about the version then...

Are you sure, that the two *.torrent* files are the same, i mean exactly the same file bit per bit?
Two *.torrent* files can be FOR the same torrent, but not being the same. Tracker addres may not be the same in our of the two file.

Can you copy (or send) the working file from your desktop computer with GUI to your linux server? Just to be sure that it's not file-related.

I can't see why it would work from the desktop app otherwise... `Failed to handle tracker response: Tracker message violates expected protocol` means that the response received by JOAL is not a tracker response.

**Comment by Ruchamimi** [comment]
Yes, I always used the same torrent freshly downloaded file for my testing. I have just tested again, with another yggtorrent account.

The torrent is downloaded today from https://www6.yggtorrent.lol/. 

If I add it using the webinterface of joal executed on my raspberry using the webinterface from my windows machine, it doesn't work (the torrent stay with ? marks on the leecher/seeder indicators, then disappear after a few seconds). the same if I copy it to the torrent directory of my rpi machine.

If I send it to joal-desktop executing from my windows machine, it does work without any issue.

I was thinking maybe my rpi machine have some config issue and cannot reach the server? They are on the same network, but it may be possible. But it's strange since the rpi machine is able to download torrent from the same tracker using qbittorent. On my raspberry, qbittorent is tunneled through a VPN, using split-tunneling with netns, only qbittorent traffic go through the VPN. It seems unlikely this would cause the issue but I prefer to give you all the details.

Any thoughts? Thanks for your help anyway.

**Comment by anthonyraymond** [comment]
Do you know how to build an image from a Dockerfile?

**Comment by Ruchamimi** [comment]
I don't but it doesn't seems complicated. Is it consisting in using the docker build command on the dockerfile, and then a docker run replacing "anthonyraymond/joal:2.1.32" with the generated image ID?

**Comment by anthonyraymond** [comment]
Yep, it's basically something like that:

- Download the source code of the special **add-trace-to-http-response** branch of this repo: [Download link](https://github.com/anthonyraymond/joal/archive/refs/heads/add-trace-to-http-response.zip)
- Extract the "add-trace-to-http-response" folder into a directory of your choice.
- From inside the "add-trace-to-http-response" folder, run the command: `docker build -t anthonyraymond/joal:temp-patchlog .`

Next:
- Stop your running container of JOAL if any
- Empty your *config/torrents* folder
- Start a JOAL container with new the image name *anthonyraymond/joal:2.1.33.patchlog*
- Add the non-working torrent to JOAL.
- Wait for the torrent to fail
- Send me the log from start to end (it may include sensitive data like IP, passkey and so on). If you prefer you can send it to joal.contact@gmail.com. But don't forget to ping me in this ticket to tell me that you've sent me an email :)

**Comment by Ruchamimi** [comment]
Thanks, the mail has just been sent.

**Comment by anthonyraymond** [comment]
The error i see from your log seems different from the original error. But the version upgrade could explain why the error message has changed, the errors handling may have change in JOAL code.

The answer you are receiving from the tracker does not makes sense though...
I don't understand how this is happening if the desktop version and qbittorrent works for the same torrent..

Don't you have some internal routing rules of soem sort that could redirect the request somewhere else?

**Comment by Ruchamimi** [comment]
Whqt really puzzles me is that it is functionnal with other trackers such as Sharewood.

I have not set any internal routing rules (I don't reaaly now how to do that). I only have a reverse proxy for routing request from my domain name toward *arr ecosystem, but nothing fancy.

Do you think having a torrent file from ygg would help? I can send you one by email, or send you the credentials from a functionnal dummy account that I have (I have no personal info on it, it linked to a temporary email adress)

**Comment by anthonyraymond** [comment]
Actually i do have a ygg torrent file. and it works for me 😆  i don't get it.

From your server can you issue the commands:

1. To open a shell in the container 
```
docker exec -it <joal_container_id> /bin/bash
```

2. To investigate:
```
apt update
apt install -y traceroute
traceroute -T -p 8080 serv.supertracker.org
```

And again send the output to the email joal contact email please :)

**Comment by Ruchamimi** [comment]
I don't get it neither... It was working before, I don't know what I changed but it's likely something on my server and not a bug from joal.

Traceroute sent by email. Not looking very good. What is weird is it give a totally different result from the container compare to from the server terminal. Is that normal?

**Comment by anthonyraymond** [comment]
It's normal to have a different output from the container compared to the server because the container add a network layer on top of the host. But it shouldn't be too much different one from another.

I'm running out of idea on this topic :/

having a tcpdump of the tracker request may (or may not) help diagnose further. But i have not idea how to do that in linux 😞 .

**Comment by Ruchamimi** [comment]
That's what is weird. Traceroute from docker only show the tracker. Traceroute from server terminal see my ISP and many additional lines.

Anyway that is likely a misconfiguration on my server and not joal issue. Thanks for your help !

**Comment by anthonyraymond** [comment]
Sorry i can't help 😟
