### ISSUE TITLE
WebUI via Docker does not update torrent speed

### ISSUE THREAD

**Issue by rursache** [anthonyraymond/joal#176]
None of my torrents from the WebUI will update their speeds, for 30min+ already they are all stuck at their initial speeds. 
How can i fix this?

A pause button for each torrent would also be nice. Or some kind of automatically stop after x time
Thanks

**Comment by anthonyraymond** [comment]
Speed will change from time to time to prevent linear speed. Don't worry about that. On top of that a randomizing coefficient is added in the background.

I suggest you use a wider speed change in configuration: from 5kbps to 60kbps for example. The change of speed will be more significants

**Comment by rursache** [comment]
@anthonyraymond 
Can you fix the UI to actually display the current speed? It should change constantly not only hourly or whatever. And if it does that, why isn't it correctly displayed in the WebUI?
Thanks

**Comment by anthonyraymond** [comment]
It must not change every second or so. it's actually better to change the way it does.

Torrent client report the amount of upload once every 30 minutes (most of the time). If i were to constantly change the speed every second il will end up in a linear upload speed every 30 minutes.
Generating random values over and over each second will produce a linear speed in the end.

It's better to change the speed less often. The best scenario is to have multiple torrents in JOAL and to set a wide enough speed configuration.

**Comment by rursache** [comment]
Thanks for the clarifications
