### ISSUE TITLE
Docker compose logs throwing TLS handshake errors and can't access webui

### ISSUE THREAD

**Issue by gravelfreeman** [anthonyraymond/joal#186]
I'm setting up my first docker compose image ever and it appears it's yours! I've spent the whole day figuring out how to get the image running. I'm having many errors in the log, this is as far as I could go before running out of ideas and resources.

Thank you for helping!

EDIT: Added log with colors https://controlc.com/9dfdb1a6

**Comment by laur89** [comment]
This is not an issue with the service, but with your docker runtime.
Good 'ol reboot doesn't help? Looks like you might have updates some dependencies. But it's just a guess.

**Comment by anthonyraymond** [comment]
Not sure what kind of log is that. But as laur89 already said. Those are not joal logs.
What command have you issued to see those logs?
