### ISSUE TITLE
add force upload feature

### ISSUE THREAD

**Issue by PowerfulRichard** [anthonyraymond/joal#188]
Please add the force upload feature to force joal to continue uploading, even when the leecher = 0.

Some trackers don't provide leecher or seeder info, they show N/A in qbittorent and 0 in joal, so even though I know there is leecher at this point, joal doesn't work.

thank you for your work !

**Comment by anthonyraymond** [comment]
Hello,

I'm sorry but i don't plan to add that. That would be too risky for most users.
