### ISSUE TITLE
Options to turn off archiving of torrent file

### ISSUE THREAD

**Issue by sickoo0** [anthonyraymond/joal#198]
I get a lot of "Hit and Run" because torrent files are moved automatically to the archived folder, is it possible to turn it off?

**Comment by anthonyraymond** [comment]
Torrent can be remove for two reasons:
- Having 0 leecher
- Fail to query tracker more than 5 times in a row

The later one can not be avoided, you can prevent 0 leechers torrents to be archived by setting the config `keepTorrentWithZeroLeechers` to `true`
