### ISSUE TITLE
output logs

### ISSUE THREAD

**Issue by nephaste** [anthonyraymond/joal#2]
Hi thanks for this project..

i am building a package for Qnap NAS with JOAL

any chance to have a flags with output debug logs ?

i am tweaking with : $JAVA -jar jack-of-all-trades.jar $MY_CONFIG_FOLDER_PATH > JOAL.log

but not really reliable... if have any idea

**Comment by anthonyraymond** [comment]
Hi nephaste,

I got it, i'll send you feedback soon, i'm thinking about it.

**Comment by anthonyraymond** [comment]
I'm on it.

Does a logfile in `MY_CONFIG_FOLDER_PATH/logs` suits your needs?

**Comment by anthonyraymond** [comment]
Well,
This project use log4j2, you'll be able to tweek logging easily.

Create the file `MY_CONFIG_FOLDER_PATH/log4j2.xml` and add this content to it:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration shutdownHook="disable">
    <Appenders>
        <File name="FileAppender" fileName="${sys:logFilename}" append="false">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </File>
        <Async name="Async">
            <AppenderRef ref="FileAppender"/>
        </Async>
    </Appenders>
    <Loggers>
        <Logger name="org.apache.log4j.xml" level="all"/>
        <Root level="INFO">
            <AppenderRef ref="Async"/>
        </Root>
    </Loggers>
</Configuration>
```
This file is your logger configuration.


And then, start your java application with : 
```
java -Dlog4j.configurationFile=file:$MY_CONFIG_FOLDER_PATH/log4j2.xml -DlogFilename=$LOGFILE_PATH -jar jack-of-all-trades.jar $MY_CONFIG_FOLDER_PATH
```
Be sure to :
- Set `$LOGFILE_PATH` with the **absolute** path of the logfile (like so: /var/log/joal.log or whatever path your want)
- Have `$MY_CONFIG_FOLDER_PATH` being an **absolute** path

**Comment by nephaste** [comment]
thanks a lot, it works   ;)

**Comment by anthonyraymond** [comment]
No problem :smile
Glad to help.
