### ISSUE TITLE
Pre-fill connection settings in WebUI

### ISSUE THREAD

**Issue by seth100** [anthonyraymond/joal#201]
Hi,

I'm using latest Docker version and, since I remove all browser data every day, it's a bit tiring for me to always set again connection settings in WebUI (by clicking on the "Change connection settings" button).
Is there a way to automatically tell WebUI to pre-fill server address, server port, path prefix, secret token fields with values I want?

Thanks

**Comment by seth100** [comment]
@anthonyraymond I tried exactly what you said but it does not work for me. It falls back to `http://localhost:{myport}/{myprefix}/ui/#/`

**Comment by anthonyraymond** [comment]
My bad, i was missing the `"` in the json, i've fixed my above message, give it another try.

**Comment by seth100** [comment]
@anthonyraymond great, it works now, thanks!
