### ISSUE TITLE
Comment rajouter de nouveaux clients ?

### ISSUE THREAD

**Issue by BreakingVap** [anthonyraymond/joal#202]
Bonjour, en ce moment, le client transition se met beaucoup à jour dans ses numéros de versions.
Comment ajouter pour la version desktop UI de votre application, les nouvelles versions de clients ?
Merci

**Comment by jimsaye** [comment]
Salut.
de mon coté j'ai copié un fichier de conf clients et je l'ai modifié avec le bon numéro de version et renommé .cela semble fonctionner

**Comment by anthonyraymond** [comment]
Bonjour,

c'est en effet la méthode utilisée, mais il y a parfois plusieurs valeurs a modifier et il faut faire attention a ce qu'on fait en regarder ce qu'envoi le vrai client.

**Comment by anthonyraymond** [comment]
Je n'ai pas beaucoup de temps en ce moment pour analyser les changements de transmission 3 => 4.

Depuis le fichier transmission.3.0.0.client, je peux vous dire que pour passer de la 3.0.0 à 3.0.4 il faut changer **au moins**

`"inclusiveUpperBound": 4294967295`
`"prefix": "-TR4030-"`
`{ "name": "User-Agent", "value": "Transmission/4.0.3" },`
```

Ce que je ne peut pas vous dire pour le moment c'est est-ce que le reste à changer ou pas. Et modifier juste ces valeurs peut s’avérer dangereux.
