### ISSUE TITLE
Some torrents fail to announce 

### ISSUE THREAD

**Issue by chrisdma** [anthonyraymond/joal#204]
Some torrents for me all from the same tracker are reporting 0 seeders/leechers, and then fail to announce. Any way to fix this? 
![3CC9AD75-70E0-45E3-841E-ED338ED5D690](https://user-images.githubusercontent.com/43798323/236113975-b1187668-03a7-4ce1-beb2-867d544d53ec.jpeg)

**Comment by chrisdma** [comment]
> Soe tracker don't report seeders/leechers properly, there is a workaround that i need to implement to circumvent this issue but i don't have time to do so ATM.
> 
> The fail can have many causes. Is it the same subset of torrent that fails? Do they successfully announce at least once?

This is the log sfter moving them from archived to the main torrent folder:

```[INFO ] 2023-05-04 11:30:20.123 [   annnouncer-1] o.a.j.c.t.c.a.Announcer: [{=B»ç0àöù`®1îþ6$¿Ñì] has failed to announce 1. time
[INFO ] 2023-05-04 11:30:20.123 [   annnouncer-0] o.a.j.c.t.c.a.Announcer: [»a! ²xÙe'eØÀéç] has failed to announce 1. time
[INFO ] 2023-05-04 11:30:20.123 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: [îFÔÂZÍ85TH.V] has failed to announce 1. time
[INFO ] 2023-05-04 11:30:26.215 [   annnouncer-1] o.a.j.c.t.c.a.Announcer: {=B»ç0àöù`®1îþ6$¿Ñì has announced successfully. Response: 0 seeders, 0 leechers, 1800s interval
[INFO ] 2023-05-04 11:30:26.215 [   annnouncer-0] o.a.j.c.t.c.a.Announcer: îFÔÂZÍ85TH.V has announced successfully. Response: 0 seeders, 0 leechers, 1800s interval
[INFO ] 2023-05-04 11:30:26.232 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: »a! ²xÙe'eØÀéç has announced successfully. Response: 0 seeders, 0 leechers, 1800s interval```

is there sny other project like this you recommend in the mean time? I deleted the source data thinking it would work with this and need to at least meet two days of seeding lol..

**Comment by anthonyraymond** [comment]
The only other tool i'd suggets is **mRatio**. Take a look at it :)

**Comment by anthonyraymond** [comment]
i've just came back to the refactorign aftre a huge break :D. Don't expect JOAL V3 to be ready before a year tough...
