### ISSUE TITLE
Is it possible to change the interval?

### ISSUE THREAD

**Issue by benrobaglia** [anthonyraymond/joal#208]
Hi, 
I saw that the seed interval is 1800s. Is it possible to change it manually, in the config file for example?

Thanks!

**Comment by anthonyraymond** [comment]
Hello,

No you can't change the interval. This is tracker dependant. I'm not
controlling this value, it's choosen by the tracker and send to the clients.


Le lun. 12 juin 2023, 13:09, Benoit ROBAGLIA ***@***.***> a
écrit :
