### ISSUE TITLE
Error when accessing dashboard "Can Upgrade only to WebSocket"

### ISSUE THREAD

**Issue by alpha90007vpn1** [anthonyraymond/joal#209]
I tested Joal out about a week back and it worked perfeactly fine.
I downloaded the same release again today and tried to run it with the same configuration and I got an error.

The webpage says ```Can "Upgrade" only to "WebSocket".```
In the browser console the error shows up as an error 400.
and the log from the Joal daemon itself shows the following error
```
[http-nio-8585-exec-5] o.s.w.s.s.s.DefaultHandshakeHandler: "Handshake failed due to invalid Upgrade header: null"
```
I am not using any reverse proxy and all of this is happening behind the local network.
Additionally this error shows up even when accessing from the same device

**Comment by HugoFollic** [comment]
Hi, I'm struggling with the same issue. How did you manage to solve it ?

**Comment by palijn** [comment]
Hi, 
for the sake of future readers.
I met the same issue and finally found it was my mistake.
Instead of using http://x.y.z.t/SECRET_OBFUSCATION_PATH one should be using http://x.y.z.t/SECRET_OBFUSCATION_PATH **/ui/** to reach the UI. (space added to allow the bold formatting)
