### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by cloud27** [anthonyraymond/joal#212]
Hello,

I have installed Joal on k3s and configure all for ui access.
I can access to ui, config with red button and have the great message "Connected to joal".
But few seconds after this message I have the message loop "Connection lost to joal...", "Connected to joal", ...

In my console I have :
`CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: '', type: 'close', …}
isTrusted
: 
true
bubbles
: 
false
cancelBubble
: 
false
cancelable
: 
false
code
: 
1006
composed
: 
false
currentTarget
: 
WebSocket {url: 'wss://xxx/xxx', readyState: 3, bufferedAmount: 194, onerror: null, onopen: ƒ, …}
defaultPrevented
: 
false
eventPhase
: 
0
reason
: 
""
returnValue
: 
true
srcElement
: 
WebSocket {url: 'wss://xxx/xxx', readyState: 3, bufferedAmount: 194, onerror: null, onopen: ƒ, …}
target
: 
WebSocket {url: 'wss://xxx/xxx', readyState: 3, bufferedAmount: 194, onerror: null, onopen: ƒ, …}
timeStamp
: 
14743
type
: 
"close"
wasClean
: 
false
[[Prototype]]
: 
CloseEvent`

webSocket is already in CLOSING or CLOSED state. webstomp.js:718

Do you have any idea ?

Thanks

**Comment by cloud27** [comment]
Sorry I found.
When I deactivate my VPN it works.
My bad.

**Comment by anthonyraymond** [comment]
More often than not this comes from a network equipment between your browser and the server.

The websocket connection between you and the server get closed by something (could be a reverse proxy, or so) which has a policy of cutting unused connections after x seconds.
