### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by fengguowudi** [anthonyraymond/joal#213]
STOMP 'CONTENT-LENGTH' HEADER VALUE 5585610 EXCEEDS CONFIGURED BUFFER SIZE LIMIT 5120000

**Comment by anthonyraymond** [comment]
This may happen if you try to use a .torrent file greather than 5Mo.

**Comment by anthonyraymond** [comment]
Use torrents smaller than 5Mo ^^

Usualy those *Huge* torrent files come from public tracker.

**Comment by wefalltomorrow** [comment]
> Use torrents smaller than 5Mo ^^
> 
> Usualy those _Huge_ torrent files come from public tracker.

Is there a reason JOAL doesn't support large torrent files?
