### ISSUE TITLE
[Request] Is there a way to change what port JOAL uses for torrents?

### ISSUE THREAD

**Issue by Aholicknight** [anthonyraymond/joal#216]
![firefox_20230820_shDiuKhecS](https://github.com/anthonyraymond/joal/assets/7843719/3ced8636-313f-4fb3-b843-2ec9d232e021)

I am currently using the VPN AirVPN which allows port forwarding. The default port that JOAL uses is already taken by another VPN member, and I am getting tracker errors saying it cannot connect. Would it be possible to change what port JOAL uses? Thank you!

**Comment by Aholicknight** [comment]
![firefox_20230821_AOv58UINDD](https://github.com/anthonyraymond/joal/assets/7843719/797bb20e-5e36-42ad-934e-d175f30588ff)

For now, I rebuilt the JAR and changed the port manaully.

**Comment by anthonyraymond** [comment]
So far it's not possible but a feature request already exists.
On my spare time (which i don't have much these days...) i'm working on remake the app from scratch. On this new version this feature will be included.
