### ISSUE TITLE
Jar File Error

### ISSUE THREAD

**Issue by jamiehaywood** [anthonyraymond/joal#23]
I'm having trouble getting it to load the JAR file in the CLI. 

java -Djava.net.preferIPv6Addresses=true -jar ./JackOfAllTradesApplication.java --joal-conf="/home/ja93dka/joal-2.0.9/joal-conf"

Error: Invalid or corrupt jarfile ./JackOfAllTradesApplication.java

**Comment by anthonyraymond** [comment]
Looks like you figured out. I believed you didn't started the `.jar` file. but a java file. You might have downloaded the source code instead of the release.
