### ISSUE TITLE
Problem WS

### ISSUE THREAD

**Issue by S8N02** [anthonyraymond/joal#24]
Hi,

I have a problem, the program starts without any problems
but I would like to use the interface and this one must call a web service
but I have a 403 error on the ws

Can you prove you can help me?

https://image.ibb.co/gUaPDS/Sans_titre.png

Thx

**Comment by izanagi1995** [comment]
I have the same problem

**Comment by izanagi1995** [comment]
Changing connection config (red button on top left) solved this

**Comment by S8N02** [comment]
Thx izanagi1995
problem solved
