### ISSUE TITLE
Possible to run joal in a docker on a Synology NAS

### ISSUE THREAD

**Issue by hot22shot** [anthonyraymond/joal#25]
Hi,

Nice software, just what I was looking for, do you know if it would be possible to run joal on a Synology NAS (intel proc) with docker ?

Cheers !

**Comment by anthonyraymond** [comment]
Hi,

Well i don't have a Synology NAS, but if you can install Docker and have an SSH access it should be fine.

Have you encountered some issues?

**Comment by hot22shot** [comment]
I successfully built the docker image from ssh  (it went surprisely well as I am quite new with docker) with the command you gave.
After that I'm at loss, here's my run command : 

docker run -d -p 25186:25186 
-v /volume1/docker/joal/data:/data 
--name="joal" araymond/joal 
--joal-conf="/data" 
--spring.main.web-environment=true 
--server.port="25186" 
--joal.ui.path.prefix="" 
--joal.ui.secret-token=***

When I try to reach 25186 for the web ui, I find nothing (http://localhost:25186).
If you have some clues as to where I should look for trouble (or log files, I could not find them), it would help !

**Comment by hot22shot** [comment]
OK, after numerous try/error, I'm now able reach the UI !

**Comment by anthonyraymond** [comment]
Nice :)

**Comment by hot22shot** [comment]
No problem, looking by myself did improve my understanding of docker.

**Comment by duchenean** [comment]
@hot22shot 
Please, could you explain how you achieved this ?
I'm facing the exact same problem with my Raspberry Pi. I can't connect to 
http://RPI_IP_ADRESS:PORT/PREFIX/ui
Thanks !

**Comment by anthonyraymond** [comment]
Is JOAL really running? Have you checked the log with :
`docker logs joal`
JOAL may have failed to start, that would explain why you can't reach the webui.

**Comment by hot22shot** [comment]
Did you configure a valid config.json file ? This was one of my (numerous) mistakes.

**Comment by duchenean** [comment]
Thanks guys ! after `docker logs joal` I understood what was the problem
It took 14 minutes for the RPi to launch joal. I simply didn't let him time to finish... whoops
Have a nice day !
