### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by mderouet** [anthonyraymond/joal#35]
Hi, i'm having an issue using joal. It seems like Joal is using a large amount of ram.

<img width="600" alt="capture d ecran 2018-06-30 a 01 03 23" src="https://user-images.githubusercontent.com/9265133/42118154-730c3372-7c01-11e8-94e4-c2c667079688.png">

As you can see i launch the command by the way of screen.
https://en.wikipedia.org/wiki/GNU_Screen

**Comment by anthonyraymond** [comment]
I've take a look on the source code, and i changed modified it a little bit just to be sure. A new version will be soon available.

But i pretty confident that there is no memory leak.  See this [StackOverflow post](https://stackoverflow.com/a/561450/2275818).
And Here is the heap overview on my computer.
![image](https://user-images.githubusercontent.com/7503585/42128888-f2727ba8-7cb5-11e8-9b84-28e4df468e55.png)


But here is something you can try:
try starting joal with : 
```
java -Xmx240M -jar jack-of-all-trades-X.X.X.jar --joal-conf="/path/to/joal-conf" --spring.main.web-environment=true --server.port=PORT --joal.ui.path.prefix="PATH-PREFIX" --joal.ui.secret-token="SECRET-TOKEN"
```
i've added -Xmx240M to forbid the JVM to exceed 240Mo of RAM.

Also. I strongly recommend that you update to Java 9. The defautl GC in java 9 now shrinks the heap size when the space is not claimed by actual allocated objects.

Tell me if you still have issues, i'm interested in that.

**Comment by anthonyraymond** [comment]
@mderouet is this solved?
