### ISSUE TITLE
is there a way to only seed until X ratio

### ISSUE THREAD

**Issue by foughtgeoduck** [anthonyraymond/joal#38]
Is there a way to only seed until X ratio.
so we dont have to keep monitoring it - as uploading 50gb for a 2 gig download might seem suss for example and might get flagged
Cheers

**Comment by anthonyraymond** [comment]
So far there is no way, but i may implement that in future releases

**Comment by foughtgeoduck** [comment]
Hi Guys,
just FYI, i ended up getting banned due to over-upload - it ended up putting a almost 50:1 ratio on a 10 gb torrent, would really like this feature added :p
in the mean time, i  just have to be more aware of the seeding process and keep monitoring it

**Comment by anthonyraymond** [comment]
@foughtgeoduck i've not forgot you ^^

I'm currently rewriting the project in another language which will provide more extensible code base and make joal a lot faster.
This feature is still in the "features to implement" stack ^^. Just behind UDP protocol.

**Comment by anthonyraymond** [comment]
Still working on the refactor. I kept this issue open as a feature request, i'll implement it in the future

**Comment by anthonyraymond** [comment]
Hey there,
Thanks to @ashaychangwani and @clementmoine this feature is now ready and ready to ship in the next release (2.1.36) to come in the next few days (most likely tonight)

**Comment by hellcry37** [comment]
this is great news, thank you!

**Comment by anthonyraymond** [comment]
Release 2.1.36 is available
