### ISSUE TITLE
Upcomming features in v2.0.0

### ISSUE THREAD

**Issue by anthonyraymond** [anthonyraymond/joal#4]
Feel free to discuss about features and tell me if you have idea to improve v2.0.0

## Features
- **GUI compatible**. (GUI will NOT be in this repository, JOAL is and will remain a command line tool. But it will be possible to connect a GUI with some kind of RPC or Websocket). An official Electron (for desktop) and webui are both planned as separate repositories. (follow desktop app progress at https://github.com/anthonyraymond/joal-electron)
- **More security**, joal will be able to disable himself. In case of a major bug has been detected, all joal client will be remortly shutted down. (Don't be affraid, there will be nothing on your computer that will report stats to any server, JOAL will simply check if a file is present in a certain directory in https://github.com/anthonyraymond/joal).
- **Brand new upload speed manager**, more safe and more close to real client than ever. And more performant than every seed faker.
- Ability to seed multiple torrent concurently.
- The pause between seed will be removed, it wasn't a good idea in the first place, and does not improve security. As long a JOAL will be started, it will seed.
- **Bulletproof!** v1.x.x was developped in a hurry (so far it seems to work perfectly), but v2.x.x will be insanely tested and much more extensible.
- <del>Hot-reloading JOAL configuration config.json. (This is still and idea, i'm not a 100% sure to include this features).</del>

## Done
- [x] Switch from Gson to Jackson.
- [x] Introduce spring(boot).
- [x] Make ConfigProvider injectable.
- [x] Make BitTorrentClientProvider injectable.
- [x] Make TorrentFileProvider injectable.
- [x] Turn SeedManager in components to allow injection.
- [x] <del>Try if re-enabling log4j shutdown hook is possible (currently, last announce log is skipped if not disabled).</del> [Not possible]
- [x] Make TorrentFileProvider returns MockedTorrent instead of FilePath.
- [x] Huge refactoring effort to make classes more responsible of their own state and less dependant of others classes.
- [x] Ensure core components are tested.
- [x] <del>Find a way to reduce number of Thread required to prevent critical thread (`BandwithManager`) to be put in idle state when joal is running on cheap computers like raspberry.</del> [Not needed]
- [x] Chose between RPC and Websocket (or both....) protocol to allow remote control (Stomp event messaging was chosen).
- [x] Refactor key generation to allow key refresh on (NEVER, RESTART, ANNOUNCE, TORRENT).
- [x] Add ipv6 support for tracker requests.
- [x] Rework all .clients files to take care of the new changes.
- [x] Add a config flag to completly disable web resources exposure.
- [x] Ensure exposed method won't be reachable by anybody (both websocket and http).
- [x] Add more version of µTorrent and Deluge.
- [x] Expose control over Stomp messaging.
- [x] Implement authentication for websocket. Login / password or maybe a secret token.

## Rescheduled for v2.0.1
- [x] Ensure web component are fully covered by Functional tests.
- [x] Ensure web component are fully covered by Integration tests.
- [x] Add the ability to disable JOAL for all users by checking if a file is present on the GitHub repository (in case a major bug has been detected and thus making the usage unsafe).
- [x] Add the ability to dispatch message to users by reading a file present on the GitHub repository.
- [x] Replace SimpleMessageBrocker with FullFeaturedMessageBrocker (http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-stomp-handle-broker-relay) and (https://github.com/BijanVan/Spring-Boot-Websocket-Sample/blob/master/src/main/java/com/bijansoft/spring/config/WebSocketConfig.java)
- [x] Write Stomp messaging documentation.

**Comment by iHmD** [comment]
seed multiple files at once?

**Comment by anthonyraymond** [comment]
I mean that you'll be able to seed more than one torrent concurently

**Comment by iHmD** [comment]
Woops it was there! sorry

**Comment by JourneyOver** [comment]
except there is a bug with it currently (reported it in slack)

**Comment by anthonyraymond** [comment]
I'll take a look at that asap

**Comment by Z-42PO** [comment]
a param in the config file to choose a port or a range of ports would be great :)

**Comment by anthonyraymond** [comment]
Why not. I'll add it on v2.0.0 or 2.0.1.

**Comment by Z-42PO** [comment]
Cool, thanks :)

**Comment by anthonyraymond** [comment]
Some major improvements have been made on v2 beta.

If you want to join beta tester let me know.

**Comment by Hexalyse** [comment]
Do you have an estimate release date for the v2 ? If it's not in a near future, I'd be glad to join the beta test. (I was hesitated to checkout the v2-dev branch but wasn't sure it will be functionnal)

**Comment by anthonyraymond** [comment]
Yep checkout the dev-v2 might not be a good idea it integrate undocumented features.

It is planned for a relative near future (before christmass) but if you are interested in beta testing send a mail at joal.conact@gmail.com.

I'll reply to you with a slack invite

**Comment by Hlidskialf7** [comment]
There is anyway to set upload until reaches ratio 1.0?

**Comment by anthonyraymond** [comment]
Not yet, and it's not planned in a near future. I'm not saying that i'll never implement this functionnality, but it is not planned yet.
