### ISSUE TITLE
web ui authorization issue

### ISSUE THREAD

**Issue by mikezhuo1022** [anthonyraymond/joal#42]
Everything works fine until the last step, the web ui refuse to access  for authorization issue.
I guess it is because password was set and the environment wasn't set up right, but i've no idea how to fix this. What may i do for this issue?

BTW, thx for great try on this repo.

**Comment by anthonyraymond** [comment]
Hi, sorry for the delay.

I'm not sure what is the problem honestly, the authentication is not prone to bugs. Hare you sure that you filled out all of the 4 field in the connection form (You can fill them by clicking the big red button on the top left corner)?

**Comment by mikezhuo1022** [comment]
That's fine. :)

Yeah, I know it is not a bug, but just dont know how to figure out the solution. I did fill the form, added my server confg., and i changed the confg.json also, then tried to run Joal on both clear OS and OS with Nginx/apache, all failed to reach the web ui.

And, one more error, After run the script(i mean without web IU), after i closed the ssh window, it stoped(maybe it lost connection w/ tracker). Should I need keep ssh window opened during the time?

**Comment by anthonyraymond** [comment]
All process started over SSH are killed upon disconnection (expect for some way of starting process, or docker, etc). This will explain why it stopped after you quit the SSH session.
But it does not explains why the webui didn't respond. Did you closed the SSH after you had navigated to localhost:xxxx and before you attempted to authenticate?

**Comment by mikezhuo1022** [comment]
Thank you for your reply and works on this repo.

For Web UI issue: i test again, it couldn't be reached even with the ssh session opened. did you run it success? or did it request a KVM based VM or OS stuff?

A suggestion: Could it possible to keep the process running without SSH session? think about it, it could much improve the convenience, also a big reason why we choose to set up the script on a server...

**Comment by anthonyraymond** [comment]
Hi,

Well i'm not such a fan of the screen command, mainly because i don't know it pretty well. And i rather use docker to run these kind of stuffs.

But about the Webui, i'm pretty suprised that it still not work.

Can you send me **at this email** : joal.contact@gmail.com :
- A screenshot of the command you are using to start joal
- A screenshot of the connection form filled up in the webui.
- A screenshot of the Google Chrome (or Firefox) console (<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>I</kbd> in Chrome or firefox)
