### ISSUE TITLE
Trackers don't seem to be updating, even after multiple passes of the timeout 

### ISSUE THREAD

**Issue by ashaychangwani** [anthonyraymond/joal#43]
I've been seeing 2 torrents for about 3 hours now, and the trackers don't seem to have updated at all. On the private torrent website, they generally update instantly, and the website still shows my upload from QBittorent, but not from Joal

**Comment by anthonyraymond** [comment]
Hi, on which tracker did you seen this? And which client are you using?

**Comment by anthonyraymond** [comment]
Close due to no answer.
