### ISSUE TITLE
ERROR 403 Webui

### ISSUE THREAD

**Issue by Brandit36** [anthonyraymond/joal#45]
Hello,

When I try to access the web interface of joal with the appropriate command, I have an access error "HTTP ERROR 403".

Can you help me ?

Thank you in advance.

Command : 
java -jar ./joal/jack-of-all-trades-2.1.7.jar --joal-conf="mypath" --spring.main.web-environment=true --server.port="myport"--joal.ui.path.prefix="mypath" --joal.ui.secret-token="mdp"

PS : Si tu es français on n'est pas obligé de le faire en anglais ;)

**Comment by anthonyraymond** [comment]
If you are getting 403 you most likely miss-spelled the URL:

http://localhost:port/SECRET_OBFUSCATION_PATH/ui/

Don't you forgot to replace the SECRET_OBFUSCATION_PATH with the value of yours ? (which must be the same as `joal.ui.path.prefix`

or don't you forgot the /ui/ part?

PS: je réponse en anglais ou cas ou quelqu'un ai le  même souci un jour ^^

**Comment by anthonyraymond** [comment]
Well it might be some shenanigans with the content of the path prefix:

Can you mail me :
- The command you used to start JOAL (with all arguments)
- The url you are trying to access (hide the domain name or ipaddress but leave the rest intact in the screenshot)

at joal.contact@gmail.com

**Comment by Brandit36** [comment]
Ok, it's done.

**Comment by anthonyraymond** [comment]
@pogla 
Hi, yes we eventually find out why.

Brandit used a `path.prefix` that contained multiples <kbd>/</kbd>. This value muse not contains only alphanumerics characters.
I've edited the readme to specify that.
