### ISSUE TITLE
Working with a reverse proxy nginx ?

### ISSUE THREAD

**Issue by m333w** [anthonyraymond/joal#46]
Hi,

I am interresting by your project, can you tell me if it can ru behind a reverse proxy nginx ?

Best regards.

**Comment by anthonyraymond** [comment]
Hi,

Sure it works, i use it behind a nginx

**Comment by anthonyraymond** [comment]
There are two valid examples in this issue https://github.com/anthonyraymond/joal/issues/33 (for both nginx and apache)
