### ISSUE TITLE
Systemd init script ?

### ISSUE THREAD

**Issue by ochbob** [anthonyraymond/joal#47]
Hello,

I just found out this awesome tool, everything works great, good job !
I was wondering if there is a way to run the jar file as service at boot with a systemd script ?

[Unit]
Description=Joal

[Service]
ExecStart=/usr/bin/java -jar /opt/joal/jack-of-all-trades-2.1.7.jar --joal-conf="/opt/joal/"

[Install]
WantedBy=multi-user.target

some things like that would work?

Thank you :)

**Comment by anthonyraymond** [comment]
Well... i don't know systemd that much since i use docker for these kind of things.

The best i can do is to give you a [link that looks like a good tutorial about systemd services](https://medium.com/@sulmansarwar/run-your-java-application-as-a-service-on-ubuntu-544531bd6102).

**Comment by ochbob** [comment]
Thank you, I will take a look and come back to say if it works :)

**Comment by ochbob** [comment]
Here we go, it works :)

Here my joal.service:

```
[Unit]
Description=Joal as Service
After=sys-devices-virtual-net-tun0.device
Wants=sys-devices-virtual-net-tun0.device

[Service]
User=XXXXX
Group=XXXXX

WorkingDirectory=/opt/joal
ExecStart=/opt/joal/StartingJoal.sh

SuccessExitStatus=143
TimeoutStopSec=10
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
```

And my script StartingJoal.sh which am I calling

```
#!/bin/sh

/usr/bin/java -jar /opt/joal/jack-of-all-trades-2.1.7.jar --joal-conf="/opt/joal/" --spring.main.web-environment=true --server.port=9493 --joal.ui.path.prefix="XXXXXX" --joal.ui.secret-token="XXXXXXXXXX"
```

**Comment by anthonyraymond** [comment]
Nice :)
well done !
