### ISSUE TITLE
Torrent tracker has changed !

### ISSUE THREAD

**Issue by elyaB** [anthonyraymond/joal#5]
Have you seen that the torrent tracker adress from t411 has changed ? JOAL is not working anymore ! I tried to re-download some new torrent since the migration, but it doesn't change anything.

**Comment by anthonyraymond** [comment]
Hi elyaB, i saw indeed. But everything is working fine, what error JOAL returns?

**Comment by elyaB** [comment]
" [bt-announce(..334574)]  WARN  org.araymond.joal.ttorent.client.announce.Announce - Error reading tracker response! "

**Comment by anthonyraymond** [comment]
I just saw this error few minutes ago on someone else computer.

I bet that if you open your `.torrent` with a text editor you'll see : `http://t411.download` instead of the new tracker adress.

It looks like t411 has kind of an issue at the moment when writting tracker adress on the fly. (probably another cache issue....).

Try downloading another torrent and double check if it has the new tracker adress.

**Comment by elyaB** [comment]
Before sending you the issue I removed all my old torrents from the torrents directory, and add 3 new torrents. I just checked, all of them refers to the new tracker !

**Comment by anthonyraymond** [comment]
Would you mind if i connect to your computer through teamviewer?

**Comment by elyaB** [comment]
not at all, but you have to explain me !

**Comment by anthonyraymond** [comment]
Install [TeamViewer](https://www.teamviewer.com/en/download/windows/) on your computer.

When installed, open it and send me your ID and Password (on the left pane) by mail joal.contact@gmail.com

**Comment by elyaB** [comment]
Wait, my bad, I'm so sorry, i restart JOAL and now it works.... Thank you for your time

**Comment by anthonyraymond** [comment]
No problem.
Glad to hear it works again :). You may have forgot to restart since putting new `.torrent` files in conf folder.

See you.

**Comment by anthonyraymond** [comment]
Désolé je n'avais pas vu la seconde partie de ton message.
C'est car tu n'avais pas du redémarré JOAL, du coup il avait encore ne mémoire le fichier qu'il était en train d'utiliser. Il sais prendre les fichier ajouté en cours de marche, ainsi que ceux que tu supprime, mais le fichier qu'il utilise actuellement est chargé en mémoire, donc il continue de l'utiliser jusqu'a la fin de la session de seed.
