### ISSUE TITLE
Add Ktorrent

### ISSUE THREAD

**Issue by abrvham** [anthonyraymond/joal#50]
Hello,
Ktorrent is the default torrent present in Kubuntu (KDE Plasma).
Could you please add it to the supported torrent programs?
Thank you

**Comment by anthonyraymond** [comment]
I'll need some time to investigate if it's possible or not, but i'll definely consider adding it :)

At the moment i'm slightly refactoring the web-ui, a new release should been available soon with some new gadgets like a dark theme. After that i'll take a look

**Comment by anthonyraymond** [comment]
Closing in favor of #99
