### ISSUE TITLE
[Question ?] This tool allow us to spoof over a PB ? like 20Exabytes ?

### ISSUE THREAD

**Issue by ruCyberPoison** [anthonyraymond/joal#52]
Yes i know, Exabytes is to much to able some one to download this size, but i would like to know if this tool return the same issue than Ratio Master have, the Ratio Master return a issue from the C# code where they have used some string like (Int64) and this limits the size to 64 bits, if i'm correct. This string is ''some limitations of '' Ratio Master Spoofer gives, I just would like to know if with you spoofer i can spoof over a Exabyte in 30 Minutes.

In one night with Ratio Master i have spoofed 5.36Eb(Exabyte) i would like to reach 500Eb,however i know this is may be unuseful but just to keep informed if your spoofer have that limitation ?

Rgds,
Cyber P.

**Comment by anthonyraymond** [comment]
At the moment such practice won't be considered safe. Overflow can occurs. But it's something that i need to address, and i'll do that address.

I'll fix that in further release :)

I'll keep you updated.

**Comment by anthonyraymond** [comment]
Well...

Actually, you can seed : 9223372 Terabytes until an overflow would occur. So i feel like i'll let it that way. Introducing `BigInteger` would impact performance.

**Comment by ruCyberPoison** [comment]
Nice to know that 👍 
I will test if it's working nicely, and i forked it right now :wink:
