### ISSUE TITLE
iFrame support?

### ISSUE THREAD

**Issue by romquenin** [anthonyraymond/joal#54]
Hello i'm using joal since yesterday and it's working perfectly, thank you i love this feature.

I would like to use Joal with Organizr to able able to centralise everything. However Joal refuse to load whithin the app in iFrame mode. When i set it to new tab it works but out of the Organizr interface.

I understand thats maybe due to the extra "/joal/ui/" in the adress after the port.

I have tried to reverse proxy whithout success.

Do you know if both iframe and reverse proxy are possible or not.

Thanks.

**Comment by hot22shot** [comment]
Hello,

I didn't try with Oragnizr but it does work with a reverse proxy (tried with a Synology).

**Comment by romquenin** [comment]
Hi, i applied the reverse proxy following this expemple:
https://primalcortex.wordpress.com/2015/12/20/synology-dsm-reverse-proxy-part-2/
 
Unfortunately it doesn't solve the Iframe problem.

**Comment by hot22shot** [comment]
I happen to also use Organizr but like you I can't make it work with JOAL.
But I tend to think that it is an Organizr issue and not a JOAL problem.

**Comment by romquenin** [comment]
The problem is most likely from Joal side.

I'm using Home Assistant and this domotic server allow to display iframe tabs. So i have tested Joal's tab and it's not working, no ui displayed.

**Comment by anthonyraymond** [comment]
When joal is in an iframe, if you open your Google Chrome console, do you see an error something like the following : `in a frame because it set 'X-Frame-Options' to 'deny'.` ?

**Comment by romquenin** [comment]
Hello i have found this :

> Load denied by X-Frame-Options: http://MYADRESS.ddns.net/api/ does not permit framing.

Hope i can help you.

**Comment by anthonyraymond** [comment]
Ok, i see what's wrong.

I'll be able to fix that but i'll need some time because i completly reworking the desktop app. But i'll include your fix in future upgrades ;).

Keep you updater

**Comment by romquenin** [comment]
That would be awsome thanks @anthonyraymond.

Could you also add a button to upload the torrents, i haven't found  a way to do it from a tablet or a mobile phone.

Would buy you a coffee if the option was available.

Thank you.

**Comment by anthonyraymond** [comment]
Hi there :)

You can download the new [2.1.13 version](https://github.com/anthonyraymond/joal/releases/tag/v2.1.13), there is now a optional `joal.iframe.enabled` parameter.
If you run joal with `--joal.iframe.enabled=true` it will enable the iframe ability.

**Comment by romquenin** [comment]
Awsome, many thanks @anthonyraymond !
