### ISSUE TITLE
Request "Put torrent in pause"

### ISSUE THREAD

**Issue by Modged** [anthonyraymond/joal#56]
Hello,

I would like you to add pause status on a specific torrent.

**Comment by anthonyraymond** [comment]
What if instead you'd have the ability to restore removed torrents, will that suits your needs?

**Comment by anthonyraymond** [comment]
no answer

**Comment by Modged** [comment]
Hello Anthony I had some problems I am so sorry for the late reply it would be a good feature too but it doesnt achieve the feature request as I expect but it would work in my case =)
The aim if you remember, I have low connection speed, 3mbits, so I set low upload speed to seems legit, it works fine with multiple torrents from the same tracker but if I want to upload to other one I have to remove the torrents of "main" tracker.
Another goal would be to separate the torrents by trackers what do you think about it ?
Thanks by advance (jumped from 2.1.17 to 2.1.24 still working like a charm and you saved me so much frustration cause we can't fight seedboxes

**Comment by anthonyraymond** [comment]
Hello modged,
Why do you want to split the torrents by tracker? What's the goal behind this, there may be a way to fix your issue without havign a new feature.

**Comment by Modged** [comment]
Because I cant remember when I have added a torrent, since when its seeding, which ratio, which tracker, and I cant stop them.
So its difficult to manage them I am still not banned but I am sure I have a very unbalanced ratio on some of them.
The other problem behind this, if a torrent has a good amount of seeders and leechers it will use the 100% or near of the upload speed (The normal behaviour) but if I want to upload a bit to another tracker I have to remove the favourite torrent of the current tracker.
I don't know if you understand what I mean I have noticed you are french I am too your english is better than mine so maybe it would be easier for both if the next is in french what do you think about it ?

**Comment by anthonyraymond** [comment]
Hello,

i'm french as well but i prefer using english language in Github issues, everyone can venefit from it in english, french is a lot more restrictive.

I undersand the problem. So far there is nothing like that and it's also not planned for the new version, but the next big feature i'll be implmenting is a way to keep torrent stats between sessions to prevent "not knowing where on a particular torrent".

But that's not to be expected in a near future though, there is still a lot of work to do before that ^^
