### ISSUE TITLE
Add Joal to Docker Hub

### ISSUE THREAD

**Issue by Adrimau** [anthonyraymond/joal#57]
Hi!

I'm using Docker on my NAS Synology to run Docker container and there's a GUI to DL, create and run/manage container. Usually I use the search bar to DL something but I can't find "anthonyraymond/joal" (it use Docker Hub as source).

Is it possible to add it to Docker Hub? It would be easier for every Synology user to run Joal!
Thanks in advance.

**Comment by anthonyraymond** [comment]
Hi,

I was thinking about that, but i'll need some more time to end my refactoring on the desktop app. But at some point i will definely upload the container to dockerhub

**Comment by romquenin** [comment]
It would be perfect, for now all images available on dockerhub are outdated. I have tried to create one without success, so I'm stuck on s8n02's version.

**Comment by anthonyraymond** [comment]
Done 😃 
Image is now available from : https://hub.docker.com/r/anthonyraymond/joal
The 2.1.14 tag is multi arch (as will be the next tags) but this requires to enable experimental features on your docker install. (If you are running amd64 you won't need to bother just use this tag).

If by anyway you want to run that on a raspberry (arm architectures) other tags are available.
