### ISSUE TITLE
webui: path prefix error?

### ISSUE THREAD

**Issue by bipox** [anthonyraymond/joal#59]
Hi,

Thank you for Joal, it's a neat little software.

I launch joal like this
`java -jar ./jack-of-all-trades-2.1.11.jar --joal-conf=/home/moi/joal/ --spring.main.web-environment=true --server.port=10001 --joal.ui.path.prefix=SECRET_OBFUSCATION_PATH --joal.ui.secret-token=SECRET`

both path and secret are alphanumerical. I've tried with and without quotes around the secrets

Seeding work but webui won't connect. It says: 
`Request was sent to URI '/' and does not match the path prefix, therefore the request Thread has been shut down`

I connect to http://localhost:10001/SECRET_OBFUSCATION_PATH/ui/ but connection fails

I have made this work before, but now that I've reinstalled it I can't figure out what I'm doing wrong.

merci!

**Comment by anthonyraymond** [comment]
Does the path prefix contains some weird symbols like `/` `\` `$`  or something like that?

**Comment by bipox** [comment]
No, only letters and numbers. 

J'ai essayé avec juste 4 chiffres pour tester, pareil.

**Comment by anthonyraymond** [comment]
Just updated my above answer, should be it

**Comment by bipox** [comment]
Yup, you were right, it works now :sweat_smile:

Désolé pour le dérangement et encore merci pour cette appli !

**Comment by anthonyraymond** [comment]
No problem ;)
