### ISSUE TITLE
Start joal at boot

### ISSUE THREAD

**Issue by Donokami** [anthonyraymond/joal#6]
Hi!
I have a Raspberry Pi and i would like to start Joal at boot, without getting me to do it manually.
How is it possible? Thanks !
---
(j'repasse en français car c'plus spécifique) une simple question, est-ce que seeder des torrents blacklistés par Hadopi via Joal m'expose à des risques ou pas, vu qu'on seed pas vraiment? Merci :)

**Comment by anthonyraymond** [comment]
Hi donokami, if you have a raspberry you can definely use docker to accomplish this task. (see the readme).

But if you don't want to use Docker you can still follow this guide : https://www.raspberrypi.org/documentation/linux/usage/rc-local.md

There is an important warning that you must take care of :
```
If your command runs continuously (perhaps runs an infinite loop) or is likely not to exit, you must be sure to fork the process by adding an ampersand to the end
```

so the command will loke like : `java -jar jack-of-all-trades-X.X.X.jar <MY_CONFIG_FOLDER_PATH> &` (notice the ampersand)

**Comment by anthonyraymond** [comment]
Pour la seconde partie de la question la réponse est obscure car on ne sais pas si Hadopi puni la présence sur la liste des seeder, ou si il faut que tu ai envoyé un paquet de données. Dans le doute évite les.

**Comment by Donokami** [comment]
It works perfectly, thanks !
I've tried using screen in rc.local, which works with my other bots, but doesn't work with joal apparently.
---
Sinon pour Hadopi j'vais faire le test, osef si j'me prends une lettre, ça permettra d'avoir un retour.

**Comment by anthonyraymond** [comment]
Parfait,
par contre si j'était toi je jouerai pas trop avec hadopi, ils chopent pas grand monde, mais vaut mieux éviter de jouer a la roulette russe. Si tu recoit une lettre tu n'aura plus d'avertissement, la prochaine fois ils couperont ton abonnement internet.

**Comment by Donokami** [comment]
![](https://www.hadopi.fr/sites/default/files/page/images/Schema_Reponse_Graduee_0.png)
ça va, et la peine maximale encourue est une amende de 1500€. Ils peuvent plus couper les abonnements internet si mes souvenirs sont bons, car l'accès à Internet est désormais reconnu comme un droit fondamental. Puis si ils m'envoient une lettre, j'émettrais une lettre de contestation.

**Comment by anthonyraymond** [comment]
Ah je savait pas, ca sert réellement plus a rien hadopi maintenant. Tant mieux.
