### ISSUE TITLE
Ability to set custom upload speed per torrent

### ISSUE THREAD

**Issue by deadpansociety** [anthonyraymond/joal#60]
There are times when I'm hunting for BP only and don't want to fake upload to tracker or there're partial seeders and I don't want to show upload data. In cases like that upload speed is inherited from what's been set in global config. It'd be helpful to have per torrent based upload speed.

**Comment by anthonyraymond** [comment]
That's not something what you could achieve in JOAL, And this is not something that i would like to implement. I understand the use case but i feel like it's an overwhelming feature for most of the users out there.

If you don't want seed at all you can set your max speed to 0 in the settings. And if you still want to accumulate BP you may download dead torrent from the tracker (like an old and useless software) or a text file that nobody will ever want or so.
