### ISSUE TITLE
Upgrade to java 11

### ISSUE THREAD

**Issue by anthonyraymond** [anthonyraymond/joal#63]
- [x] Take a look at java 9 modules
- [x] Decide if it's worth for joal (Won't hurt, and the code may actually be more friendly with it, let's do it)
- [ ] Make use of Java 9 modules
- [ ] Assert that it works on java 11 locally
- [ ] Update CI build environment to Java 11
- [ ] Update Docker image to run on java 11
- [ ] Update README and other docs
- [ ] Update the desktop app to download openjdk 11

**Comment by anthonyraymond** [comment]
Canceled:
I'm rewriting the project in Golang, this issue i not relevant anymore.

**Comment by sleaze** [comment]
@anthonyraymond Is the Golang rewrite code available anywhere?  I bet it's amazing, would love to DL and have a look!

**Comment by anthonyraymond** [comment]
Hi @sleaze,

I'm working on it but it can not be downloaded yet (mostly because it's not working yet ^^, the program still miss some critical feature to be usable).
The code reside in a private repo so far. i plan to override this repo when the new version will be in stable state.
I'l probably open an issue in some time to ask for beta tester if you are interested be sure to "watch" the project ;)
