### ISSUE TITLE
Login page User - pasword

### ISSUE THREAD

**Issue by bilyboy785** [anthonyraymond/joal#66]
Hello,

i've got a login page : 

![Login page](https://i.imgur.com/eX8gSlT.png)

use docker compose, and when i point to @IP:PORT/joal/ui, it's redirect to this login page .. How can i fix it ?

**Comment by bilyboy785** [comment]
There is my docker compose : 

```
joal:
    restart: always
    image: anthonyraymond/joal
    container_name: joal
    network_mode: bridge
    ports:
      - "5081:5081"
    volumes:
      - ${ROOT}/Dockers/joal:/data
    command: ["--joal-conf=/data", "--sprint.main.web-environment=true", "--server.port=5081", "--jaol.ui.path.prefix=joal", "--joal.ui.secret-token=example"]
    environment:
      - VIRTUAL_HOST=${JOAL_DOMAIN}
      - LETSENCRYPT_HOST=${JOAL_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}```

**Comment by anthonyraymond** [comment]
Well... I don't know what that is but it's not joal, have you set up somenkins of a reverse peoxy as well?

**Comment by bilyboy785** [comment]
I just use Jwilder like my other apps.
even without using the proxy, I am redirected to this page. I have to run joal with docker run for everything to be OK

**Comment by anthonyraymond** [comment]
What happens if you go to : 
 - http://YOUR_LOCAL_IP:5081/blabla/ui

Is it the same as http://YOUR_LOCAL_IP:5081/joal/ui ?

**Comment by Powkq** [comment]
Hi,

Got the same problem, i'm running JOAL locally

**Comment by anthonyraymond** [comment]
> There is my docker compose :
> 
> ```
> joal:
>     restart: always
>     image: anthonyraymond/joal
>     container_name: joal
>     network_mode: bridge
>     ports:
>       - "5081:5081"
>     volumes:
>       - ${ROOT}/Dockers/joal:/data
>     command: ["--joal-conf=/data", "--sprint.main.web-environment=true", "--server.port=5081", "--jaol.ui.path.prefix=joal", "--joal.ui.secret-token=example"]
>     environment:
>       - VIRTUAL_HOST=${JOAL_DOMAIN}
>       - LETSENCRYPT_HOST=${JOAL_DOMAIN}
>       - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
> ```

Well !! 3 month later with a second look i can see an error with: `sprint.main.web-environment` (supposed to be `spring` not `sprint`)

**Comment by Powkq** [comment]
I'm running joal with plain java locally.
Here is the command I use:
```
java -jar ./jack-of-all-trades-2.1.18.jar --joal-conf="PATH TO JOAL" --sprin.main.web-environnement=true --server.port=5081 --joal.ui.path.prefix="joal" --joal.ui.secret-token="secret"
```

Everything just works fine, except the web-ui (redirected to a login page).

Also, my config.json file:
```
{
  "minUploadRate": 30,
  "maxUploadRate": 170,
  "simultaneousSeed": 5,
  "client": "utorrent-3.5.0_43916.client",
  "keepTorrentWithZeroLeechers": true
}
```

**Comment by anthonyraymond** [comment]
Same deal,

You have a typo in sprin**g**.main.web-environnement

**Comment by Powkq** [comment]
Oh my bad !

Didn't pay attention to the typos of the command...
Now everything's working just fine !

But do you know what is the purpose of the login page ?
It's reachable only when joal is running.

**Comment by anthonyraymond** [comment]
It might be a part of the web framework i use. It enables some behaviour by default, this might be one of those and it's not disabled because a joal param was missing, so it was in the middle of two stable states (with or without webui & authentication)
