### ISSUE TITLE
Connection settings not static

### ISSUE THREAD

**Issue by soflane** [anthonyraymond/joal#68]
Hey Anthony, 

First of all, great project !! I was wondering having something like this on Linux instead of Windows, you saved me weeks of work!

I have a little annoyment tho, the "connection settings" are always cleared up if you browse the page on a different device. 
I protected the web UI with a htaccess so the config should be enough. But when my cookies are flushed, I need to reconfigure the settings. Kinda annoying when using it with 2 other people at my place. 
I there maybe a way, to hardcode it somewhere? 
I was searching in the source code but couldn't find it. 

Thanks already for the work you did.

**Comment by anthonyraymond** [comment]
Hi @soflane 

Indeed, the connection string acts as a login process, it's a per device mechanism. Credentials are stored in the `localstorage`.

There is no need to clear history & cookies when you leave the computer, as long as the other user in your house use a different windows/linux session. Chrome won't share the localstorage among OS sessions. IMO it's a bit redundant to use a htaccess.


But if you wish, there is actually a undocumented way to autologin to the webui, using an url parameter:

**1) Define json object with proper auth values**
First create a json object with the proper values for your joal instance :
```
{
  host: 'localhost',
  port: 5081,
  pathPrefix: "ilovejoal",
  secretToken: "andTheseUndoccumentedFeatures"
}
```
The values are the one you'd put in the connection form.


**2) Uri encode the json object**
Then you'll need to uri encode this json object. You can paste your text on [this](https://meyerweb.com/eric/tools/dencoder/) site and click on encode.

Then copy the your text (which should looks quite weird by now, with a lot of %), mine looks like this:
```
%7B%0A%20%20host%3A%20%27localhost%27%2C%0A%20%20port%3A%205081%2C%0A%20%20pathPrefix%3A%20%22ilovejoal%22%2C%0A%20%20secretToken%3A%20%22andTheseUndoccumentedFeatures%22%0A%7D
```

and go to your joal webui 

**3) Pass the uri parameter to the webui**
Navigate your joal's webui with the following uri param:

http://<span></span>localhost:5081/ilovejoal/ui?**ui_credentials=**%7B%0A%20%20host%3A%20%27localhost%27%2C%0A%20%20port%3A%205081%2C%0A%20%20pathPrefix%3A%20%22ilovejoal%22%2C%0A%20%20secretToken%3A%20%22andTheseUndoccumentedFeatures%22%0A%7D

**Comment by soflane** [comment]
Hi, 

Thanks for your reply. 

I tried it but it doesn't seems to work. When I try to browse the URL with the param, the param variable is removed. 

Example : 
If I browse : 

http://localhost:5081/ilovejoal/ui?ui_credentials=%7B%0A%20%20host%3A%20%27localhost%27%2C%0A%20%20port%3A%205081%2C%0A%20%20pathPrefix%3A%20%22ilovejoal%22%2C%0A%20%20secretToken%3A%20%22andTheseUndoccumentedFeatures%22%0A%7D

It immediately switch to : 

http://localhost:5081/ilovejoal/ui/#


And what I see in the logs is : 
 [WARN ] 2019-05-05 11:53:07.641 [http-nio-5081-exec-7] o.a.j.w.c.o.AbortNonPrefixedRequestFilter: Request was sent to URI '/' and does not match the path prefix, therefore the request Thread has been shut down.


You have an idea ?

**Comment by anthonyraymond** [comment]
The autoremoval is normal, but the webui should be automatically connected thanks to the URL param.

Are you not connected after being redirected?

**Comment by soflane** [comment]
No, it doesn't unfortunately...

It only gets the fail to login notification at the upper right corner and
when I check the settings, the default ones are still in place.
And what I see when I do a docker logs is that line mentioned above.



Le lun. 6 mai 2019 à 23:41, Anthony Raymond <notifications@github.com> a
écrit :

**Comment by anthonyraymond** [comment]
Woops, you were right.

I've missused the uri decoding. It's now fixed, new joal version has been released through Github and Docker hub. Should work now.

https://hub.docker.com/r/anthonyraymond/joal/tags

**Comment by soflane** [comment]
Still nothing, same behavior and same logs

**Comment by anthonyraymond** [comment]
Ok, i know what is going on.
The website does not add quotes around the json attributes, here is what you need to do :

For the part 1)

Use this json instead (note the quotes around the attributes) :
```
{
  "host": "localhost",
  "port": 5081,
  "pathPrefix": "ilovejoal",
  "secretToken": "andTheseUndoccumentedFeatures"
}
```

Then go ahead with the rest of the process

**Comment by soflane** [comment]
Thanksssss it works !!!! 
I close it 
Thanks !!
