### ISSUE TITLE
Auto-download unseeded torrents from T411(suggestion)

### ISSUE THREAD

**Issue by Donokami** [anthonyraymond/joal#7]
Encore une suggestion, serait-ce possible d'ajouter un système qui télécharge automatiquement des torrents non-seedés en provenance de t411, pour augmenter son ratio sans rien faire du tout? :)
Je sais pas du tout si c'est possible ou pas, je suggère juste !
Merci :+1:

**Comment by anthonyraymond** [comment]
Ben il est prévu pour être utilisé sur tous les trackers. Donc je ne prévoit pas d'intégré des comportements spécifique à un seul tracker dans le projet. Mais je garde l'idée dans un coin quand j'aurai bien avancé dans le projet et que la v2 sera sortie.

**Comment by Donokami** [comment]
Pas de soucis !
