### ISSUE TITLE
Null pointer on announce

### ISSUE THREAD

**Issue by KonstantinKuklin** [anthonyraymond/joal#73]
Hi, I use last version.
Always get 0 seeders and 0 leechers and in logs such messages:
> [WARN ] 2019-06-04 05:28:54.070 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: Cà=¶1Nô has failed to announce
> java.lang.NullPointerException
> 	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
> 	at java.base/java.util.Optional.<init>(Optional.java:106)
> 	at java.base/java.util.Optional.of(Optional.java:119)
> 	at org.araymond.joal.core.client.emulated.BitTorrentClient.getKey(BitTorrentClient.java:61)
> 	at org.araymond.joal.core.client.emulated.BitTorrentClient.createRequestQuery(BitTorrentClient.java:111)
> 	at org.araymond.joal.core.ttorrent.client.announcer.request.AnnounceDataAccessor.getHttpRequestQueryForTorrent(AnnounceDataAccessor.java:25)
> 	at org.araymond.joal.core.ttorrent.client.announcer.Announcer.announce(Announcer.java:64)
> 	at org.araymond.joal.core.ttorrent.client.announcer.request.AnnouncerExecutor.lambda$execute$0(AnnouncerExecutor.java:40)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by anthonyraymond** [comment]
Hello.

Does this happens only with one torrent or all of thel

**Comment by KonstantinKuklin** [comment]
I added 4 and this message on all of 4. 
But without --debug program says all ok, announced successful

**Comment by anthonyraymond** [comment]
What client and version are you using in joal? (visible through the webui or in the config.json file)

**Comment by KonstantinKuklin** [comment]
cat config.json 
```json
{
  "minUploadRate": 30,
  "maxUploadRate": 700,
  "simultaneousSeed": 20,
  "client": "utorrent-3.5.0_43916.client",
  "keepTorrentWithZeroLeechers": true
}
```

**Comment by anthonyraymond** [comment]
I Can't reproduce on my side, does it still happens if you choose another torrent? And with another tracker?

**Comment by KonstantinKuklin** [comment]
Yes, checked again on another torrent and torrent server - same result
`java -jar ./jack-of-all-trades-2.1.17.jar --spring.main.web-environment=true  --debug --server.port=1145 --joal-conf="/path/to/joal.tar" --joal.ui.path.prefix="aaa" --joal.ui.secret-token="sec"
`
with torrent https://filebin.net/beqwxii6tyfl509h/_KinoGB.net_Bogi.Egipta_Gods.of.Egypt.2016.BDRip.AVC.ot.HELLYW.torrent?t=9ztscssu

gives
![image](https://user-images.githubusercontent.com/573586/60544661-edc36d00-9d21-11e9-971a-cf349a669e21.png)

**Comment by anthonyraymond** [comment]
I'm sorry, i've been pretty busy these times and now the pastebin has expired. Could you reup it please?

PS: send the link to joal.contact@gmail.com, the torrent file contains your passkey if you are using a private tracker

**Comment by Dark-Mickey** [comment]
I have exactly the same problem, but only on my VPS, not on my PC (debian / virtualbox)

**Comment by anthonyraymond** [comment]
@Dark-Mickey 
Hi, i'm currently rewritting JOAL in another language, this issue will be auto-solved with the new version. But it takes some times, i expect it to be ready in the next few months.
