### ISSUE TITLE
Joal sur un raspberry pi 3 ARM avec Raspbian

### ISSUE THREAD

**Issue by chicungunya** [anthonyraymond/joal#74]
Salut
Tout d’abord merci d’avoir crée cette application . 
Je souhaite l’installer sur un Pi 3 ARM avec Raspbian mais je n’y arrive pas. (Joal Desktop)
Pourrais tu me guider please ?
Si non est ce qu’il y a une alternative ?
Merci beaucoup !

**Comment by anthonyraymond** [comment]
Salut, désolé pour le delai de réponse.

C'est un raspbian avec une interface graphique? C'est quoi que tu n'arrive pas a faire exactement?

**Comment by chicungunya** [comment]
Hello @anthonyraymond 
J'ai réussi finalement, c'est pour ca que j'ai fermé le ticket.
Merci beaucoup!
