### ISSUE TITLE
Login page when accessing the web-ui

### ISSUE THREAD

**Issue by Powkq** [anthonyraymond/joal#76]
Hi,

I got the same problem discussed in this issue: #66 
I am running joal locally and when I try to access the web-ui I am redirected to a login page.

Thanks for your help !

**Comment by anthonyraymond** [comment]
How do you use joal? 
Run with plain `java` command, docker run, docker-compose, is it part of a docker swarm?

also can you share your config.json and the command that you use to run the app?

**Comment by anthonyraymond** [comment]
See my comment at #66 and let me known if you are in this case, otherwise i'll be interested by your answer to this above post.
