### ISSUE TITLE
Installation with Docker GUI (Synology)

### ISSUE THREAD

**Issue by Sayukat** [anthonyraymond/joal#77]
Hi,

I'm trying to install Joal with the Docker GUI on Synology, but I'm stuck, where and how should I place the following command in the below window ?

 --joal-conf="/data" \
 --spring.main.web-environment=true \
 --server.port="PORT" \
 --joal.ui.path.prefix="SECRET_OBFUSCATION_PATH" \
 --joal.ui.secret-token="SECRET_TOKEN"

![4](https://user-images.githubusercontent.com/23632812/61636496-06c29c80-ac96-11e9-91e1-b7c474eadc95.jpeg)

Thanks for your help,
Have a Nice day,
Siegfried

**Comment by anthonyraymond** [comment]
It has to be in the "Command" text box, each arguments separated by spaces:

`--joal-conf="/data" --spring.main.web-environment=true --server.port="PORT" --joal.ui.path.prefix="SECRET_OBFUSCATION_PATH" --joal.ui.secret-token="SECRET_TOKEN"`

**Comment by Sayukat** [comment]
Hi,

Thanks for your.

I did this but I get the following message : "Run command format error."

below is the command I try to use:

--joal-conf="/data" --spring.main.web-environment=true --server.port="9000" --joal.ui.path.prefix="joal" --joal.ui.secret-token="04500796"

Am I missing something ?

Thanks for your help,
Have a nice day,
Siegfried

**Comment by anthonyraymond** [comment]
Could you also try those formats and let me known if of those one works for you?

`--joal-conf "/data" --spring.main.web-environment=true --server.port "9000" --joal.ui.path.prefix "joal" --joal.ui.secret-token "04500796"`

or

`--joal-conf /data --spring.main.web-environment true --server.port 9000 --joal.ui.path.prefix joal --joal.ui.secret-token 04500796`

or

`--joal-conf=/data --spring.main.web-environment=true --server.port=9000 --joal.ui.path.prefix=joal --joal.ui.secret-token=04500796`or

**Comment by Sayukat** [comment]
Hi

I just tried all those formats, but without success, here is what I get : 

`--joal-conf "/data" --spring.main.web-environment=true --server.port "9000" --joal.ui.path.prefix "joal" --joal.ui.secret-token "04500796"`

> _**---> "Run command format error."**_


`--joal-conf\="/data" --spring.main.web-environment\=true --server.port\="PORT" --joal.ui.path.prefix\="joal" --joal.ui.secret-token\="04500796"`

> _**---> I can finish the setup, but then the Joal container is using full CPU, crash and restart over and over again**_


`--joal-conf /data --spring.main.web-environment true --server.port 9000 --joal.ui.path.prefix joal --joal.ui.secret-token 04500796`

> _**---> I can finish the setup, but then the Joal container is using full CPU, crash and restart over and over again**_


`--joal-conf=/data --spring.main.web-environment=true --server.port=9000 --joal.ui.path.prefix=joal --joal.ui.secret-token=04500796`

> _**---> "Run command format error."**_

**Comment by anthonyraymond** [comment]
Can you send the `docker logs` for command 2 and 4 between each reboot please?

**Comment by Sayukat** [comment]
Hi,

Actually command 2 is working

`--joal-conf\="/data" --spring.main.web-environment\=true --server.port\="PORT" --joal.ui.path.prefix\="joal" --joal.ui.secret-token\="04500796"`

I forgot the change PORT by (in my case) 9000. So the correct command is :

`--joal-conf\="/data" --spring.main.web-environment\=true --server.port\="9000" --joal.ui.path.prefix\="joal" --joal.ui.secret-token\="04500796"`

Thanks for you time and patience,
Have a great day

**Comment by anthonyraymond** [comment]
Nice :)
No problem.

**Comment by Adrimau** [comment]
Hi @Sayukat, I got exactly the same need as you but the web UI doesn't work. Did you have this problem? https://github.com/anthonyraymond/joal/issues/80#issuecomment-530238522

**Comment by Altecco** [comment]
> 
> 
> Hi,
> 
> I'm trying to install Joal with the Docker GUI on Synology, but I'm stuck, where and how should I place the following command in the below window ?
> 
> --joal-conf="/data"
> --spring.main.web-environment=true
> --server.port="PORT"
> --joal.ui.path.prefix="SECRET_OBFUSCATION_PATH"
> --joal.ui.secret-token="SECRET_TOKEN"
> 
> ![4](https://user-images.githubusercontent.com/23632812/61636496-06c29c80-ac96-11e9-91e1-b7c474eadc95.jpeg)
> 
> Thanks for your help,
> Have a Nice day,
> Siegfried

Hello Siegfried,

Is it possible for you to describe your entire setup step by step ?
By following your issue I'm stuck too with the same issue, but using your command line didn't solved my problems.

First error was "folder not found /data/torrents", I created in the volume section and now its /data/config.json

I'm not sure 'im using correctly :(

Regards,
Julien.

**Comment by RenardFox** [comment]
Hello,
I am really sorry to open the discussion again but I am very interested in having the wonderful tool Joal on my Synology but it is the first time I use Docker and I must admit I don't understand the installation process.

Here are my info:
 - Synology : DSM 7.1.1-42962 Update 1
 - Docker : 20.10.3-1308
 - I downloaded via Docker the latest version of joal via Docker:
![image](https://user-images.githubusercontent.com/26163608/213943067-ca00ee56-5f27-46f1-9644-0acaa0402a88.png)

Now I tried, to configure it following some comment mentionned here or https://github.com/anthonyraymond/joal/issues/80#issuecomment-530238522
But each time, I launched it, the application stopped after few seconds. And I am quite sure I don't do the right things.

Do you have a Tutorial somewhere to be able to install it ?
Do I need to put the joal-conf/ folder somewhere on my synology ?
I must admit, I a bit lost, and I don't really understand what I am doing.

Soory for that, and overall... Thanks a lot for your help and support !

**Comment by anthonyraymond** [comment]
Hello,

You need to have the joal-conf folder somewhere indeed, and shared to th edocker container as a volume...
Unfortunately i don't known anything about synology :/ i'm won't be able to help you on that.
Maybe someone on that thread that got it to work on Synology might help you?

Also, i'm not so much into GUI when it comes to docker, i always spent too many times searching for things that requires only 10 char in a shell.
If you can issue a `docker` command from a terminal in Synology i may offer some help to sort things out but i can't on the Synology GUI.

**Comment by RenardFox** [comment]
Thanks a lot @anthonyraymond for your quick answer. I will try to use the command line in synology and check the results. I'll keep you posted.

Thanks again.
