### ISSUE TITLE
Have a random seed rate per torrent

### ISSUE THREAD

**Issue by mystikxkemix** [anthonyraymond/joal#79]
Hi,

Right now joal configuration only allows to fix a _total_ seed rate.
The problem is that, right now, some torrents may seed to a really high rate, and others can seed to a really low rate 

![Capture d’écran 2019-08-08 à 17 32 11](https://user-images.githubusercontent.com/9988890/62716461-81afe500-ba02-11e9-881d-f181fbe926ad.png)

It should be usefull to say that we only want a range rate per torrent

**Comment by mystikxkemix** [comment]
I have just noticed something : it seems that joal get the torrent upload rate from a ratio between the amount of seeders and leechers.

Is it correct ?

**Comment by anthonyraymond** [comment]
That's it.

Having 0 leechers or 0 seeders is a no-go for the ratio, it will remove the torrent (or seed at 0 if the "keep torrent wiht zero peers" config is checked).

Other than that:
- Each torrent get a weight based on seeder / leechers calculations (see [formula available here](https://github.com/anthonyraymond/joal/blob/master/src/main/java/org/araymond/joal/core/bandwith/weight/PeersAwareWeightCalculator.java))
- The bandwidth (a random speed value chosen once every 20 minutes) is now splitted among all torrents, the more weight it has the more bandwidth it gets.

Note that the bandwidth is a value between "min upload speed" and "max upload speed" config

**Comment by 9521520** [comment]
@anthonyraymond 
When you said "lower value (min=10, max=100)",

Dose this value suits for one torrent? or for the whole Joal total upload rate?

example like:
when I seed 10 torrents simultaneously, is it ok to seed in a rate between 100 to 1000kB/s ?

**Comment by anthonyraymond** [comment]
@9521520 It's the overall limit (for the whole joal upload rate).

100 to 1000Kb is pretty high imo. If you let joal running for a day il will generate between 8.6 and 86GB per day. I'd recommend lower value somewhere like between 0 and 150kb/s

**Comment by 9521520** [comment]
> @9521520 It's the overall limit (for the whole joal upload rate).
> 
> 100 to 1000Kb is pretty high imo. If you let joal running for a day il will generate between 8.6 and 86GB per day. I'd recommend lower value somewhere like between 0 and 150kb/s

I see, many thanks!!
