### ISSUE TITLE
Joal with Docker in Synology NAS

### ISSUE THREAD

**Issue by Adrimau** [anthonyraymond/joal#80]
Hi!
I'm not very friendly with Docker in command line so I would like to install Joal in Docker on my Synology NAS (with the GUI).

How am I supposed to enable the Joal's webui? I tried with an environment variable but it doesn't work.

Thanks in advance.

**Comment by anthonyraymond** [comment]
Take a look at this issue
https://github.com/anthonyraymond/joal/issues/77#issuecomment-521256656

**Comment by Adrimau** [comment]
Thanks for your message.

I tried like the other post:
`--joal-conf\="/data" --spring.main.web-environment\=true --server.port\="2001" --joal.ui.path.prefix\="mypath" --joal.ui.secret-token\="mytoken"`

I haven't any error in the log but http://ip:port/mypath/ui/ is unavailable

**Comment by anthonyraymond** [comment]
i'm affraind i won't be able to help you much more than that :/ i don't known synology and i don't have one to invetigate

**Comment by CorentinGC** [comment]
> I tried with `--joal-conf\="/data" \ --spring.main.web-environment\=true \ --server.port\="9001" \ --joal.ui.path.prefix\="joal" \ --joal.ui.secret-token\="mytoken"` and it works when I put a .torrent file, but the UI still disable (http://myNASip:9001/joal/ui/)

You have to add a port redirection on container settings , from outside port of your choice to defined port on --server.port=PORT
<img width="647" alt="Capture d’écran 2019-11-24 à 03 15 15" src="https://user-images.githubusercontent.com/1381160/69488356-b9835100-0e68-11ea-8306-b8514a48c696.png">

I can access the UI, but the websocket are trying to connect to /, but the path is /joal/  :/

**Comment by anthonyraymond** [comment]
You need to change the connection settings using the red button on the top left of joal UI.

From there you'll be asked to enter ws connection informations (including the path)

**Comment by CorentinGC** [comment]
I just saw that ! Damn ^^ 
All is working like a charm, thank you :) !

**Comment by Adrimau** [comment]
Thanks for the tips about port. Got same issue as you. I'm accessing to the UI with http://ip:port/prefix/ui, so I tried to put "prefix/ui" as path prefix and I doesn't work either.

The URL in the console is "ws://ip:port/prefix/ui", should works no?
