### ISSUE TITLE
Joal behind haproxy

### ISSUE THREAD

**Issue by guidzou** [anthonyraymond/joal#81]
I've configured joal behind my firewall, on which I use an haproxy to handle/distribute http requests.
I don't find any way to make it work properly. I have the main part of the page, but seems like next http requests don't use the good path :
In tcpdump, (made on public internet side of haproxy ) firsts requests have a proper 'GET /joal/ui/ HTTP/1.1'
But following ones have a simple 'GET / HTTP/1.1' which is refused by joal since it doesn't match the path prefix (/joal/ui in my testing case).

My haproxy is very simple :
          frontend http
             bind *:80
             mode http
             default_backend joal
          backend joal
             mode http
             server joalwww <joal_ip>:<joal_port>

Would you have an explaination for this behaviour ?

![Capture](https://user-images.githubusercontent.com/55592443/65336236-48a08e00-dbc6-11e9-814a-70465d6d2b32.JPG)

**Comment by anthonyraymond** [comment]
I don't know haproxy at all, but if this thread should help you out https://github.com/anthonyraymond/joal/issues/33

Ther eis valid examples for both nginx and apache2 reverse proxy.
