### ISSUE TITLE
Client Files for uTorrent v2.2.1, build 25130

### ISSUE THREAD

**Issue by SumitBajoria** [anthonyraymond/joal#87]
Hello,

Been using joal for about 6 months now and I must commend you for the effort you have put in. 

Can you please add client files for uTorrent v2.2.1, build 25130.

Thanks!

**Comment by anthonyraymond** [comment]
Hello, 
Thanks for your support.
I'm in the middle of re-coding joal from scratch in another language.
The result will be much more faster and probably less memory consuming.
So i'm a bit late on client files at the moment and i don't have much time to create new files atm. But i'll add them to the new joal for sure :)

Have a nice day

Le 7 déc. 2019 à 05:04, à 05:04, SumitBajoria <notifications@github.com> a écrit:

**Comment by anthonyraymond** [comment]
Closing in favor of #99
