### ISSUE TITLE
Unable to use Web UI

### ISSUE THREAD

**Issue by paeolo** [anthonyraymond/joal#89]
Hi,
Thanks for your work.
When I try to use the Web UI with the required parameter it doesn't work. The WEB UI is served but what I read is "failed to connect to joal".
On the server side the log says:
"[WARN ] 2019-12-31 22:30:15.497 [http-nio-8000-exec-3] o.a.j.w.c.o.AbortNonPrefixedRequestFilter: Request was sent to URI '/' and does not match the path prefix, therefore the request Thread has been shut down."
Paul.

**Comment by anthonyraymond** [comment]
Hi @paeolo you need to click on the red button "Change connection settings" on the top left of JOAL.

You'll be prompted for all the credentials to contact the joal server. Without those joal can not connect to the server, that's why you have these error messages.

**Comment by paeolo** [comment]
Oh my bad. It works like a charm ty!
Paul.
