### ISSUE TITLE
Questions (Possibly suggestions?).

### ISSUE THREAD

**Issue by JourneyOver** [anthonyraymond/joal#9]
So I am wanting to know, how often does this thing announce to the trackers? Currently while running tests to make sure my .client file I made is working correctly I only ever see it announce when it does a stop announcement due to the "seed for" timer hitting its mark, but so far I haven't seen any other announcements being made at all.

Is there a way to set up an "always announce to trackers" or setting a time to announce to trackers (other than the stop timer) or anything of the sort?

one more thing, "If the torrent currently seeding reach 0 peers, the file will be moved to <MY_CONFIG_FOLDER_PATH>/torrents/archived folder." is there a way to set up how many of a min you want to go on leechers before the .torrent is sent to the archive folder?

**Comment by anthonyraymond** [comment]
Hi jouney,

You can't customize time between annouce. This is a value that i grab from the tracker (usualy 30 min, but it is up to the tracker). It is even possible that the tracker set the value to 9999999 to prevent client from announcing exept for stop or complete (even if thid is dumb).

V1.x.x only support one torrent at the time, but v2.x.x (which is on alpha) will support multiple torrent concurently.

You can't customize minimum leechers on v1 as well, but it is planned for v2.

**Comment by JourneyOver** [comment]
Ah well darn haha, I do know that the tracker I'm using has a default of at least 30 minutes last time I checked, guess I just wasn't running things long enough since I was mainly just testing to see if the .client I made for qbittorrent was working correctly or not (which I have since determined that it is working correctly) 

Yea I read that you'll have multi torrent support in v2 shortly after making this post so ended up removing that question, but glad that custom min leechers and multi torrent support is coming in v2 :D will make things look at least a little more legit.

**Comment by anthonyraymond** [comment]
Hehe.

Haven't checked qbittorrent yet, but as soon as v2 wil lbe release i'll add official support for it :)
