### ISSUE TITLE
Config upload rate individually？

### ISSUE THREAD

**Issue by 9521520** [anthonyraymond/joal#90]
I have notice sometimes when a torrent had some bad internet connection leechers, 
they are actually not downloading a single byte of data from the tracker.

but in Joal, I am still making uploads, would this be obviously noticeable?

hope you see what I mean.

If that could cause a problem, 

Is there any way that I could 0 the upload rates out idividually for those torrents when I notice there are bad connection leechers?

**Comment by anthonyraymond** [comment]
Nop so far you can. It may indeed be flag by trackers but that would require human inspection, you are kind of lost in the crawd, more than than you may be sharing the file to people not using the tracker (dht and peer exchange), so... it's safe
