### ISSUE TITLE
Options to use proxy

### ISSUE THREAD

**Issue by mohu2p** [anthonyraymond/joal#91]
Hello,

I want the option to use a http proxy or socks proxy for reporting to trackers.

Thank you.

**Comment by anthonyraymond** [comment]
That's not a on deck feature, but i'll consider that for the next versions

**Comment by mohu2p** [comment]
Thank you very much.
I am glad if it is added.

**Comment by pbossert** [comment]
same request, it would be very nice to use socks5 protocl from a vpn :)
Thanks in advance

**Comment by anthonyraymond** [comment]
Hi, i'm completely rewriting the project in another language (Golang), it takes a lot of time to do and i'm pretty busy these days, So i don't develop any more feature for the current version.

It won't be a feature released with the rewrote version but i keep that in mind and i will definitely implement that in the future :)

**Comment by chicungunya** [comment]
Hello @anthonyraymond , do you have some news about this feature ? 
Thanks a lot

**Comment by anthonyraymond** [comment]
Hi, i'm still working on the full rewrite. But i don't have much time these days.
I'm dtill here the project is not abandonned, but i'm working on "invisible stuff"

**Comment by anthonyraymond** [comment]
The feature has been implemented in the rewritten version. The new version is not publicly available because still in dvelopment, but the feature is already in so i'm closing the issue now.

**Comment by Cosmonear** [comment]
Hello, Any news on this feature ?
Thank you very much.

**Comment by anthonyraymond** [comment]
Hello, still working on it, but i've took a step back to rework the entire architecture, it will take some time.
This version is not under active development anymore (appart from security fix).

**But the project is not abandoned, i'm working on it**

**Comment by heartbleeded** [comment]
bumping,
any update for this must-have feature and the new project?

**Comment by chicungunya** [comment]
Hello, SOCKS5 still not available? Thanks!

**Comment by chicungunya** [comment]
Any update @anthonyraymond ? 
Thanks!
