### ISSUE TITLE
Installation issue - docker

### ISSUE THREAD

**Issue by MartnIV** [anthonyraymond/joal#96]
Hey,

I cannot find any way to get it works, no matter how i try, i finish always with an ERR_CONNECTION_REFUSED on chrome.
What i tried:

Using docker-compose on an ubuntu running under an esxi host:
I got an another container running well, exposing one port with a web ui (Tautulli)
My docker-compose:
  joal:
    restart: unless-stopped
    image: anthonyraymond/joal
    container_name: joal
    network_mode: host
    ports:
      - "5081:5081"
    volumes:
      - /dockerdata/joal/:/data
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=5081", "--jaol.ui.path.prefix=joal", "--joal.ui.secret-token=199239"]

URL: http://localip:5081/joal/ui

Using an xpenology (debian) under an esxi host:
docker run -d \
  -p 9000:9000 \
  -v /dockerdata/joal/torrent/:/joal/torrents/ \
  --name="joal" s8n02/joal \
  --/dockerdata/joal/config/="/joal" \
  --spring.main.web-environment=true \
  --server.port=9000 \
  --joal.ui.path.prefix=joal \
  --joal.ui.secret-token=99239

URL: http://localip:9000/joal/ui

Using an ubuntu server (physical):
docker run -d \
  -p 9000:9000 \
  -v /dockerdata/joal/torrent/:/joal/torrents/ \
  --name="joal" s8n02/joal \
  --/dockerdata/joal/config/="/joal" \
  --spring.main.web-environment=true \
  --server.port=9000 \
  --joal.ui.path.prefix=joal \
  --joal.ui.secret-token=99239

URL: http://localip:9000/joal/ui

Any idea of what is happening? Do i need to install anything before?

**Comment by MartnIV** [comment]
Also I notice the config folder stay empty.

**Comment by anthonyraymond** [comment]
Hi @MartnIV if the config folder is empty you might have forgot the Step 1 in the instructions.
If after this you still have an issue, send me the terminal log

**Comment by MartnIV** [comment]
Ah ! I didnt thought I had to download the archive to get it running with docker.
Good to know. I test it and let you know. thanks.

**Comment by anthonyraymond** [comment]
@MartnIV 
Closign due to no answer, feel free to re-open if you still have problem with joal ;)
