### ISSUE TITLE
stop  announcing after running for a while

### ISSUE THREAD

**Issue by CoderCore** [anthonyraymond/joal#98]
I put more than 200 torrent  for  fake seeder.

But after running for a while,  maybe 4h - 24h  ， it stop announceing  only fetch ip。

config is:

{
  "minUploadRate" : 0,
  "maxUploadRate" : 0,
  "simultaneousSeed" : 1000,
  "client" : "qbittorrent-4.1.9.client",
  "keepTorrentWithZeroLeechers" : true
}

start cmd line is :

java -jar jack-of-all-trades-2.1.20.jar --joal-conf="/root/joal/" --spring.main.web-environment=false --debug

[INFO ] 2020-05-07 22:19:32.770 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: Û]³"y"@J9}ORµ2ý has announced successfully. Response: 193 seeders, 1 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:35.799 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: 4cÄzÌ·ú§l4õèó>| has announced successfully. Response: 35 seeders, 0 leechers, 1200s interval
[INFO ] 2020-05-07 22:19:38.059 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: ;!R}où$©kz}Åk has announced successfully. Response: 17 seeders, 0 leechers, 1200s interval
[INFO ] 2020-05-07 22:19:39.974 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: ¢TÃ¥"8ÈQÆëvøUs´ has announced successfully. Response: 141 seeders, 3 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:43.374 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: ÜûïáMRô©]cØ° v has announced successfully. Response: 48 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:44.224 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: '¥RéîÆnVÑ@ñd] has announced successfully. Response: 270 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:44.459 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: ¶cÐÜ³täë´zÕöÝ has announced successfully. Response: 367 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:44.693 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: àÃÆïvÕùh·Å±|>ÿÊ has announced successfully. Response: 383 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:44.926 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: «Á¹.®îû³Ëã]Vw has announced successfully. Response: 259 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:45.164 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: Áç½PÝùW×«#sw has announced successfully. Response: 376 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:45.394 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: P2çÜ®*jÊ{ has announced successfully. Response: 315 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:45.638 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: =Ì;VÆ¨hyÒòà6< has announced successfully. Response: 376 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:47.015 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: zWÏËZ/éÇ%Áü has announced successfully. Response: 57 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:48.718 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: õ)îZÞI;[}Nr1 has announced successfully. Response: 30 seeders, 2 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:49.659 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: ¯~¬¯¬_cSàøYè has announced successfully. Response: 283 seeders, 9 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:50.673 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: ÊøÇj$Bû Ôl has announced successfully. Response: 208 seeders, 1 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:50.957 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: äµ¾c'pÆ¸IÚä has announced successfully. Response: 314 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:51.189 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: ¢mæVPwÂýbØ{x,( has announced successfully. Response: 240 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:19:51.421 [   annnouncer-2] o.a.j.c.t.c.a.Announcer: ë³ä&ðV¨Äo:àÝ î] has announced successfully. Response: 346 seeders, 0 leechers, 3600s interval
[INFO ] 2020-05-07 22:47:32.032 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://l2.io/ip
[INFO ] 2020-05-07 22:47:34.576 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**
[INFO ] 2020-05-08 00:17:34.577 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://ident.me/
[INFO ] 2020-05-08 00:17:35.417 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**
[INFO ] 2020-05-08 01:47:35.418 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: https://tnx.nl/ip
[INFO ] 2020-05-08 01:47:37.373 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**
[INFO ] 2020-05-08 03:17:37.375 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://l2.io/ip
[INFO ] 2020-05-08 03:17:38.200 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**
[INFO ] 2020-05-08 04:47:38.201 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://ident.me/
[INFO ] 2020-05-08 04:47:39.482 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**
[INFO ] 2020-05-08 06:17:39.483 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://bot.whatismyipaddress.com/
[INFO ] 2020-05-08 06:17:39.910 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**
[INFO ] 2020-05-08 07:47:39.911 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://bot.whatismyipaddress.com/
[INFO ] 2020-05-08 07:47:40.590 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**
[INFO ] 2020-05-08 09:17:40.592 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://icanhazip.com/
[INFO ] 2020-05-08 09:17:41.187 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**
[INFO ] 2020-05-08 10:47:41.188 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://l2.io/ip
[INFO ] 2020-05-08 10:47:45.615 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**
[INFO ] 2020-05-08 12:17:45.616 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: https://tnx.nl/ip
[INFO ] 2020-05-08 12:17:47.605 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**
[INFO ] 2020-05-08 13:47:47.607 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Fetching ip from: http://ip.tyk.nu/
[INFO ] 2020-05-08 13:47:48.944 [       Thread-4] o.a.j.c.t.c.ConnectionHandler: Successfully fetch public IP address: **.**.**.**

**Comment by anthonyraymond** [comment]
Hi,
Thats is peculiar indeed 😄 

To troubleshoot that i could use a more consitent log, can you please follow the 4 steps below to produce a more verbose logging please:
 1) Create a `/root/joal/log4j2.xml` file, can you please:
 2) In this file add the following content 
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration shutdownHook="disable">
    <Appenders>
        <File name="FileAppender" fileName="${sys:logFilename}" append="false">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </File>
        <Async name="Async">
            <AppenderRef ref="FileAppender"/>
        </Async>
    </Appenders>
    <Loggers>
        <Logger name="org.apache.log4j.xml" level="all"/>
        <Root level="DEBUG">
            <AppenderRef ref="Async"/>
        </Root>
        <Logger name="org.araymond.joal" level="TRACE" additivity="false">
            <Appender-ref ref="Async"/>
        </Logger>
    </Loggers>
</Configuration>
```
 3) Use this line to start joal: `java -Dlog4j.configurationFile=file:/root/joal/log4j2.xml -DlogFilename=/root/joal/joal.log -jar jack-of-all-trades-2.1.20.jar --joal-conf="/root/joal/" --spring.main.web-environment=false
`
 4) When you notice the announces has stopped, stop JOAL and send me the `/root/joal/joal.log` file (prefer email to *joal.contact@gmail.com*) and mention this issue (n°98).

**Comment by CoderCore** [comment]
![11](https://user-images.githubusercontent.com/35726402/81479755-d3b6bd00-9257-11ea-8f44-d937fb1eb6c6.png)
 I just found out , free memory is very litter on my device.
Before that ，I run this program  on  a  Idle Tv Box , and  the  tv box  only have  1GB ram.
Later, I will try  to  run  the  program  on other  hardware with enough ram.
If the problem doesn't reappear, it can be sure that it's caused by a lack of memory.

**Comment by anthonyraymond** [comment]
The announces (http request to tracker) are split among 3 threads. But that a bit peculiar every now and then one thread seems to stop doing it's work for no reason without warning or reason.
If that was a memory issue i would have expected at least an error in the log :/ (don't know if the JVM instruct the program or just randomly kill some threads though....)

I suspect the apache http library to remain stuck in a request because each of the two threads stucks appeared on HTTP request so...

I've jut sent you a modified version of JOAL to test this out.

**Comment by anthonyraymond** [comment]
Fixed, new release incoming.
